// Generated by aps2scala version 0.3.6
import basic_implicit._;
object farrow_ubd_implicit {
  val farrow_ubd_loaded = true;
  import symbol_implicit._;
  import table_implicit._;
  import flat_implicit._;
  import farrow_ubd_tree_implicit._;
  type T_FARROW_UBD[T_T] = T_T;
}
import farrow_ubd_implicit._;

import symbol_implicit._;
import table_implicit._;
import flat_implicit._;
import farrow_ubd_tree_implicit._;
trait C_FARROW_UBD[T_Result, T_T] extends C_TYPE[T_Result]
  with C_FARROW_UBD_TREE[T_Result] {
  type T_IntegerLattice;
  val t_IntegerLattice : C_TYPE[T_IntegerLattice]
    with C_FLAT_LATTICE[T_IntegerLattice,T_Integer];
  type T_DeclPairLattice;
  val t_DeclPairLattice : C_TYPE[T_DeclPairLattice]
    with C_TABLE_LATTICE[T_DeclPairLattice,T_Symbol,T_IntegerLattice];
  type T_Messages;
  val t_Messages : C_TYPE[T_Messages]
    with C_SET[T_Messages,T_String];
  val v_decl_name : (T_Declaration) => T_Symbol;
  val v_decl_pair : (T_Declaration) => T_DeclPairLattice;
  val v_decl_env : (T_Declaration) => T_DeclPairLattice;
  val v_decl_errs : (T_Declaration) => T_Messages;
  val v_decls_defs : (T_Declarations) => T_DeclPairLattice;
  val v_decls_env : (T_Declarations) => T_DeclPairLattice;
  val v_decls_errs : (T_Declarations) => T_Messages;
  val v_expr_val : (T_Expression) => T_IntegerLattice;
  val v_expr_env : (T_Expression) => T_DeclPairLattice;
  val v_expr_errs : (T_Expression) => T_Messages;
  val v_term_val : (T_Term) => T_IntegerLattice;
  val v_term_env : (T_Term) => T_DeclPairLattice;
  val v_term_errs : (T_Term) => T_Messages;
  val v_op_val : (T_Operation) => T_IntegerLattice;
  val v_op_lval : (T_Operation) => T_IntegerLattice;
  val v_op_rval : (T_Operation) => T_IntegerLattice;
  val v_program_errs : (T_Program) => T_Messages;
}

class M_FARROW_UBD[T_T](name : String,val t_T : C_TYPE[T_T]
  with C_FARROW_UBD_TREE[T_T])
  extends Module(name)
    with C_FARROW_UBD[T_T,T_T]
{
  type T_Result = T_T;
  val v_equal = t_T.v_equal;
  val v_string = t_T.v_string;
  val v_assert = t_T.v_assert;
  val v_node_equivalent = t_T.v_node_equivalent;
  type T_Declaration = t_T.T_Declaration;
  val t_Declaration = t_T.t_Declaration;
  type T_Declarations = t_T.T_Declarations;
  val t_Declarations = t_T.t_Declarations;
  type T_Expression = t_T.T_Expression;
  val t_Expression = t_T.t_Expression;
  type T_Term = t_T.T_Term;
  val t_Term = t_T.t_Term;
  type T_Operation = t_T.T_Operation;
  val t_Operation = t_T.t_Operation;
  type T_Program = t_T.T_Program;
  val t_Program = t_T.t_Program;
  val p_scope = t_T.p_scope;
  val v_scope = t_T.v_scope;
  val p_decl_assign = t_T.p_decl_assign;
  val v_decl_assign = t_T.v_decl_assign;
  val p_decls_empty = t_T.p_decls_empty;
  val v_decls_empty = t_T.v_decls_empty;
  val p_decls_append = t_T.p_decls_append;
  val v_decls_append = t_T.v_decls_append;
  val p_decls_append_scope = t_T.p_decls_append_scope;
  val v_decls_append_scope = t_T.v_decls_append_scope;
  val p_expr_term = t_T.p_expr_term;
  val v_expr_term = t_T.v_expr_term;
  val p_op_add = t_T.p_op_add;
  val v_op_add = t_T.v_op_add;
  val p_op_mul = t_T.p_op_mul;
  val v_op_mul = t_T.v_op_mul;
  val p_op_sub = t_T.p_op_sub;
  val v_op_sub = t_T.v_op_sub;
  val p_op_div = t_T.p_op_div;
  val v_op_div = t_T.v_op_div;
  val p_expr_apply = t_T.p_expr_apply;
  val v_expr_apply = t_T.v_expr_apply;
  val p_term_variable = t_T.p_term_variable;
  val v_term_variable = t_T.v_term_variable;
  val p_term_literal = t_T.p_term_literal;
  val v_term_literal = t_T.v_term_literal;
  val p_program = t_T.p_program;
  val v_program = t_T.v_program;

  val t_Result : this.type = this;
  val t_IntegerLattice = new M_FLAT_LATTICE[T_Integer](
    "IntegerLattice",
    t_Integer
  )

  type T_IntegerLattice = /*TI*/T_FLAT_LATTICE[T_Integer];
  val t_DeclPairLattice = new M_TABLE_LATTICE[T_Symbol,T_IntegerLattice](
    "DeclPairLattice",
    t_Symbol,
    t_IntegerLattice
  )

  type T_DeclPairLattice = /*TI*/T_TABLE_LATTICE[T_Symbol,T_IntegerLattice];
  val t_Messages = new M_SET[T_String](
    "Messages",
    t_String
  )

  type T_Messages = /*TI*/T_SET[T_String];
  private class E_decl_name(anchor : T_Declaration) extends Evaluation[T_Declaration,T_Symbol](anchor,anchor.toString()+"."+"decl_name") {
  }
  private object a_decl_name extends Attribute[T_Declaration,T_Symbol](t_Declaration,t_Symbol,"decl_name") {
    override def createEvaluation(anchor : T_Declaration) : Evaluation[T_Declaration,T_Symbol] = new E_decl_name(anchor);
  }
  val v_decl_name : T_Declaration => T_Symbol = a_decl_name.get _;

  private class E_decl_pair(anchor : T_Declaration) extends Evaluation[T_Declaration,T_DeclPairLattice](anchor,anchor.toString()+"."+"decl_pair") with CircularEvaluation[T_Declaration,T_DeclPairLattice] with CollectionEvaluation[T_Declaration,T_DeclPairLattice] with StaticCircularEvaluation[T_Declaration,T_DeclPairLattice] {
    override def initial : T_DeclPairLattice = t_DeclPairLattice.v_initial;
    override def combine(v1 : T_DeclPairLattice, v2 : T_DeclPairLattice) = t_DeclPairLattice.v_combine(v1,v2);
    def lattice : C_LATTICE[T_DeclPairLattice] = t_DeclPairLattice;

  }
  private object a_decl_pair extends Attribute[T_Declaration,T_DeclPairLattice](t_Declaration,t_DeclPairLattice,"decl_pair")
    with ChangeTrackingAttribute[T_Declaration,T_DeclPairLattice] {
    override def createEvaluation(anchor : T_Declaration) : Evaluation[T_Declaration,T_DeclPairLattice] = new E_decl_pair(anchor);
  }
  val v_decl_pair : T_Declaration => T_DeclPairLattice = a_decl_pair.get _;

  private class E_decl_env(anchor : T_Declaration) extends Evaluation[T_Declaration,T_DeclPairLattice](anchor,anchor.toString()+"."+"decl_env") with CircularEvaluation[T_Declaration,T_DeclPairLattice] with CollectionEvaluation[T_Declaration,T_DeclPairLattice] with StaticCircularEvaluation[T_Declaration,T_DeclPairLattice] {
    override def initial : T_DeclPairLattice = t_DeclPairLattice.v_initial;
    override def combine(v1 : T_DeclPairLattice, v2 : T_DeclPairLattice) = t_DeclPairLattice.v_combine(v1,v2);
    def lattice : C_LATTICE[T_DeclPairLattice] = t_DeclPairLattice;

  }
  private object a_decl_env extends Attribute[T_Declaration,T_DeclPairLattice](t_Declaration,t_DeclPairLattice,"decl_env")
    with ChangeTrackingAttribute[T_Declaration,T_DeclPairLattice] {
    override def createEvaluation(anchor : T_Declaration) : Evaluation[T_Declaration,T_DeclPairLattice] = new E_decl_env(anchor);
  }
  val v_decl_env : T_Declaration => T_DeclPairLattice = a_decl_env.get _;

  private class E_decl_errs(anchor : T_Declaration) extends Evaluation[T_Declaration,T_Messages](anchor,anchor.toString()+"."+"decl_errs") {
  }
  private object a_decl_errs extends Attribute[T_Declaration,T_Messages](t_Declaration,t_Messages,"decl_errs") {
    override def createEvaluation(anchor : T_Declaration) : Evaluation[T_Declaration,T_Messages] = new E_decl_errs(anchor);
  }
  val v_decl_errs : T_Declaration => T_Messages = a_decl_errs.get _;

  private class E_decls_defs(anchor : T_Declarations) extends Evaluation[T_Declarations,T_DeclPairLattice](anchor,anchor.toString()+"."+"decls_defs") with CircularEvaluation[T_Declarations,T_DeclPairLattice] with CollectionEvaluation[T_Declarations,T_DeclPairLattice] with StaticCircularEvaluation[T_Declarations,T_DeclPairLattice] {
    override def initial : T_DeclPairLattice = t_DeclPairLattice.v_initial;
    override def combine(v1 : T_DeclPairLattice, v2 : T_DeclPairLattice) = t_DeclPairLattice.v_combine(v1,v2);
    def lattice : C_LATTICE[T_DeclPairLattice] = t_DeclPairLattice;

  }
  private object a_decls_defs extends Attribute[T_Declarations,T_DeclPairLattice](t_Declarations,t_DeclPairLattice,"decls_defs")
    with ChangeTrackingAttribute[T_Declarations,T_DeclPairLattice] {
    override def createEvaluation(anchor : T_Declarations) : Evaluation[T_Declarations,T_DeclPairLattice] = new E_decls_defs(anchor);
  }
  val v_decls_defs : T_Declarations => T_DeclPairLattice = a_decls_defs.get _;

  private class E_decls_env(anchor : T_Declarations) extends Evaluation[T_Declarations,T_DeclPairLattice](anchor,anchor.toString()+"."+"decls_env") with CircularEvaluation[T_Declarations,T_DeclPairLattice] with CollectionEvaluation[T_Declarations,T_DeclPairLattice] with StaticCircularEvaluation[T_Declarations,T_DeclPairLattice] {
    override def initial : T_DeclPairLattice = t_DeclPairLattice.v_initial;
    override def combine(v1 : T_DeclPairLattice, v2 : T_DeclPairLattice) = t_DeclPairLattice.v_combine(v1,v2);
    def lattice : C_LATTICE[T_DeclPairLattice] = t_DeclPairLattice;

  }
  private object a_decls_env extends Attribute[T_Declarations,T_DeclPairLattice](t_Declarations,t_DeclPairLattice,"decls_env")
    with ChangeTrackingAttribute[T_Declarations,T_DeclPairLattice] {
    override def createEvaluation(anchor : T_Declarations) : Evaluation[T_Declarations,T_DeclPairLattice] = new E_decls_env(anchor);
  }
  val v_decls_env : T_Declarations => T_DeclPairLattice = a_decls_env.get _;

  private class E_decls_errs(anchor : T_Declarations) extends Evaluation[T_Declarations,T_Messages](anchor,anchor.toString()+"."+"decls_errs") {
  }
  private object a_decls_errs extends Attribute[T_Declarations,T_Messages](t_Declarations,t_Messages,"decls_errs") {
    override def createEvaluation(anchor : T_Declarations) : Evaluation[T_Declarations,T_Messages] = new E_decls_errs(anchor);
  }
  val v_decls_errs : T_Declarations => T_Messages = a_decls_errs.get _;

  private class E_expr_val(anchor : T_Expression) extends Evaluation[T_Expression,T_IntegerLattice](anchor,anchor.toString()+"."+"expr_val") with CircularEvaluation[T_Expression,T_IntegerLattice] with StaticCircularEvaluation[T_Expression,T_IntegerLattice] {
    def lattice : C_LATTICE[T_IntegerLattice] = t_IntegerLattice;

  }
  private object a_expr_val extends Attribute[T_Expression,T_IntegerLattice](t_Expression,t_IntegerLattice,"expr_val")
    with ChangeTrackingAttribute[T_Expression,T_IntegerLattice] {
    override def createEvaluation(anchor : T_Expression) : Evaluation[T_Expression,T_IntegerLattice] = new E_expr_val(anchor);
  }
  val v_expr_val : T_Expression => T_IntegerLattice = a_expr_val.get _;

  private class E_expr_env(anchor : T_Expression) extends Evaluation[T_Expression,T_DeclPairLattice](anchor,anchor.toString()+"."+"expr_env") with CircularEvaluation[T_Expression,T_DeclPairLattice] with CollectionEvaluation[T_Expression,T_DeclPairLattice] with StaticCircularEvaluation[T_Expression,T_DeclPairLattice] {
    override def initial : T_DeclPairLattice = t_DeclPairLattice.v_initial;
    override def combine(v1 : T_DeclPairLattice, v2 : T_DeclPairLattice) = t_DeclPairLattice.v_combine(v1,v2);
    def lattice : C_LATTICE[T_DeclPairLattice] = t_DeclPairLattice;

  }
  private object a_expr_env extends Attribute[T_Expression,T_DeclPairLattice](t_Expression,t_DeclPairLattice,"expr_env")
    with ChangeTrackingAttribute[T_Expression,T_DeclPairLattice] {
    override def createEvaluation(anchor : T_Expression) : Evaluation[T_Expression,T_DeclPairLattice] = new E_expr_env(anchor);
  }
  val v_expr_env : T_Expression => T_DeclPairLattice = a_expr_env.get _;

  private class E_expr_errs(anchor : T_Expression) extends Evaluation[T_Expression,T_Messages](anchor,anchor.toString()+"."+"expr_errs") {
  }
  private object a_expr_errs extends Attribute[T_Expression,T_Messages](t_Expression,t_Messages,"expr_errs") {
    override def createEvaluation(anchor : T_Expression) : Evaluation[T_Expression,T_Messages] = new E_expr_errs(anchor);
  }
  val v_expr_errs : T_Expression => T_Messages = a_expr_errs.get _;

  private class E_term_val(anchor : T_Term) extends Evaluation[T_Term,T_IntegerLattice](anchor,anchor.toString()+"."+"term_val") with CircularEvaluation[T_Term,T_IntegerLattice] with StaticCircularEvaluation[T_Term,T_IntegerLattice] {
    def lattice : C_LATTICE[T_IntegerLattice] = t_IntegerLattice;

  }
  private object a_term_val extends Attribute[T_Term,T_IntegerLattice](t_Term,t_IntegerLattice,"term_val")
    with ChangeTrackingAttribute[T_Term,T_IntegerLattice] {
    override def createEvaluation(anchor : T_Term) : Evaluation[T_Term,T_IntegerLattice] = new E_term_val(anchor);
  }
  val v_term_val : T_Term => T_IntegerLattice = a_term_val.get _;

  private class E_term_env(anchor : T_Term) extends Evaluation[T_Term,T_DeclPairLattice](anchor,anchor.toString()+"."+"term_env") with CircularEvaluation[T_Term,T_DeclPairLattice] with CollectionEvaluation[T_Term,T_DeclPairLattice] with StaticCircularEvaluation[T_Term,T_DeclPairLattice] {
    override def initial : T_DeclPairLattice = t_DeclPairLattice.v_initial;
    override def combine(v1 : T_DeclPairLattice, v2 : T_DeclPairLattice) = t_DeclPairLattice.v_combine(v1,v2);
    def lattice : C_LATTICE[T_DeclPairLattice] = t_DeclPairLattice;

  }
  private object a_term_env extends Attribute[T_Term,T_DeclPairLattice](t_Term,t_DeclPairLattice,"term_env")
    with ChangeTrackingAttribute[T_Term,T_DeclPairLattice] {
    override def createEvaluation(anchor : T_Term) : Evaluation[T_Term,T_DeclPairLattice] = new E_term_env(anchor);
  }
  val v_term_env : T_Term => T_DeclPairLattice = a_term_env.get _;

  private class E_term_errs(anchor : T_Term) extends Evaluation[T_Term,T_Messages](anchor,anchor.toString()+"."+"term_errs") {
  }
  private object a_term_errs extends Attribute[T_Term,T_Messages](t_Term,t_Messages,"term_errs") {
    override def createEvaluation(anchor : T_Term) : Evaluation[T_Term,T_Messages] = new E_term_errs(anchor);
  }
  val v_term_errs : T_Term => T_Messages = a_term_errs.get _;

  private class E_op_val(anchor : T_Operation) extends Evaluation[T_Operation,T_IntegerLattice](anchor,anchor.toString()+"."+"op_val") with CircularEvaluation[T_Operation,T_IntegerLattice] with StaticCircularEvaluation[T_Operation,T_IntegerLattice] {
    def lattice : C_LATTICE[T_IntegerLattice] = t_IntegerLattice;

  }
  private object a_op_val extends Attribute[T_Operation,T_IntegerLattice](t_Operation,t_IntegerLattice,"op_val")
    with ChangeTrackingAttribute[T_Operation,T_IntegerLattice] {
    override def createEvaluation(anchor : T_Operation) : Evaluation[T_Operation,T_IntegerLattice] = new E_op_val(anchor);
  }
  val v_op_val : T_Operation => T_IntegerLattice = a_op_val.get _;

  private class E_op_lval(anchor : T_Operation) extends Evaluation[T_Operation,T_IntegerLattice](anchor,anchor.toString()+"."+"op_lval") with CircularEvaluation[T_Operation,T_IntegerLattice] with StaticCircularEvaluation[T_Operation,T_IntegerLattice] {
    def lattice : C_LATTICE[T_IntegerLattice] = t_IntegerLattice;

  }
  private object a_op_lval extends Attribute[T_Operation,T_IntegerLattice](t_Operation,t_IntegerLattice,"op_lval")
    with ChangeTrackingAttribute[T_Operation,T_IntegerLattice] {
    override def createEvaluation(anchor : T_Operation) : Evaluation[T_Operation,T_IntegerLattice] = new E_op_lval(anchor);
  }
  val v_op_lval : T_Operation => T_IntegerLattice = a_op_lval.get _;

  private class E_op_rval(anchor : T_Operation) extends Evaluation[T_Operation,T_IntegerLattice](anchor,anchor.toString()+"."+"op_rval") with CircularEvaluation[T_Operation,T_IntegerLattice] with StaticCircularEvaluation[T_Operation,T_IntegerLattice] {
    def lattice : C_LATTICE[T_IntegerLattice] = t_IntegerLattice;

  }
  private object a_op_rval extends Attribute[T_Operation,T_IntegerLattice](t_Operation,t_IntegerLattice,"op_rval")
    with ChangeTrackingAttribute[T_Operation,T_IntegerLattice] {
    override def createEvaluation(anchor : T_Operation) : Evaluation[T_Operation,T_IntegerLattice] = new E_op_rval(anchor);
  }
  val v_op_rval : T_Operation => T_IntegerLattice = a_op_rval.get _;

  private class E_program_errs(anchor : T_Program) extends Evaluation[T_Program,T_Messages](anchor,anchor.toString()+"."+"program_errs") {
  }
  private object a_program_errs extends Attribute[T_Program,T_Messages](t_Program,t_Messages,"program_errs") {
    override def createEvaluation(anchor : T_Program) : Evaluation[T_Program,T_Messages] = new E_program_errs(anchor);
  }
  val v_program_errs : T_Program => T_Messages = a_program_errs.get _;

  private class E1_variable_value(anchor : t_Result.T_Term) extends Evaluation[t_Result.T_Term,T_IntegerLattice](anchor,anchor.toString()+"."+"variable_value") with CircularEvaluation[t_Result.T_Term,T_IntegerLattice] with StaticCircularEvaluation[t_Result.T_Term,T_IntegerLattice] {
    def lattice : C_LATTICE[T_IntegerLattice] = t_IntegerLattice;

  }
  private object a1_variable_value extends Attribute[t_Result.T_Term,T_IntegerLattice](t_Result.t_Term,t_IntegerLattice,"variable_value")
    with ChangeTrackingAttribute[t_Result.T_Term,T_IntegerLattice] {
    override def createEvaluation(anchor : t_Result.T_Term) : Evaluation[t_Result.T_Term,T_IntegerLattice] = new E1_variable_value(anchor);
  }
  private class E2_variable_defined(anchor : t_Result.T_Term) extends Evaluation[t_Result.T_Term,T_OrLattice](anchor,anchor.toString()+"."+"variable_defined") with CircularEvaluation[t_Result.T_Term,T_OrLattice] with StaticCircularEvaluation[t_Result.T_Term,T_OrLattice] {
    def lattice : C_LATTICE[T_OrLattice] = t_OrLattice;

  }
  private object a2_variable_defined extends Attribute[t_Result.T_Term,T_OrLattice](t_Result.t_Term,t_OrLattice,"variable_defined")
    with ChangeTrackingAttribute[t_Result.T_Term,T_OrLattice] {
    override def createEvaluation(anchor : t_Result.T_Term) : Evaluation[t_Result.T_Term,T_OrLattice] = new E2_variable_defined(anchor);
  }
  def visit_0_1(node : T_Declaration, changed : AtomicBoolean) : Unit = node match {
    case p_decl_assign(_,_,_) => visit_0_1_0(node, changed);
  };
  def visit_0_2(node : T_Declaration, changed : AtomicBoolean) : Unit = node match {
    case p_decl_assign(_,_,_) => visit_0_2_0(node, changed);
  };
  def visit_0_3(node : T_Declaration, changed : AtomicBoolean) : Unit = node match {
    case p_decl_assign(_,_,_) => visit_0_3_0(node, changed);
  };
  def visit_0_1_0(anchor : T_Declaration, changed : AtomicBoolean) : Unit = anchor match {
    case p_decl_assign(v_self,v_s,v_e) => {

      visit_2_1(v_e, changed);
      a_decl_name.set(v_self,v_s);
    }
  }
  def visit_0_2_0(anchor : T_Declaration, changed : AtomicBoolean) : Unit = anchor match {
    case p_decl_assign(v_self,v_s,v_e) => {
      a_expr_env.set(v_e,a_decl_env.get(v_self), changed);

      visit_2_2(v_e, changed);
      a_decl_pair.set(v_self,t_DeclPairLattice.v_table_entry(v_s,
        a_expr_val.get(v_e)), changed);
    }
  }
  def visit_0_3_0(anchor : T_Declaration, changed : AtomicBoolean) : Unit = anchor match {
    case p_decl_assign(v_self,v_s,v_e) => {

      visit_2_3(v_e, changed);
      a_decl_errs.set(v_self,a_expr_errs.get(v_e));
    }
  }

  def visit_1_1(node : T_Declarations, changed : AtomicBoolean) : Unit = node match {
    case p_scope(_,_) => visit_1_1_0(node, changed);
    case p_decls_empty(_) => visit_1_1_1(node, changed);
    case p_decls_append(_,_,_) => visit_1_1_2(node, changed);
    case p_decls_append_scope(_,_,_) => visit_1_1_3(node, changed);
  };
  def visit_1_2(node : T_Declarations, changed : AtomicBoolean) : Unit = node match {
    case p_scope(_,_) => visit_1_2_0(node, changed);
    case p_decls_empty(_) => visit_1_2_1(node, changed);
    case p_decls_append(_,_,_) => visit_1_2_2(node, changed);
    case p_decls_append_scope(_,_,_) => visit_1_2_3(node, changed);
  };
  def visit_1_3(node : T_Declarations, changed : AtomicBoolean) : Unit = node match {
    case p_scope(_,_) => visit_1_3_0(node, changed);
    case p_decls_empty(_) => visit_1_3_1(node, changed);
    case p_decls_append(_,_,_) => visit_1_3_2(node, changed);
    case p_decls_append_scope(_,_,_) => visit_1_3_3(node, changed);
  };
  def visit_1_1_0(anchor : T_Declarations, changed : AtomicBoolean) : Unit = anchor match {
    case p_scope(v_self,v_ds) => {

      visit_1_1(v_ds, changed);
      {
        val newChanged = new AtomicBoolean(false);
        do {
          newChanged.set(false);
          a_decls_env.set(v_ds,a_decls_defs.get(v_ds), newChanged);

          visit_1_2(v_ds, newChanged);

        } while(newChanged.get);
      }

      visit_1_3(v_ds, changed);
    }
  }
  def visit_1_2_0(anchor : T_Declarations, changed : AtomicBoolean) : Unit = anchor match {
    case p_scope(v_self,v_ds) => {
      a_decls_defs.set(v_self,a_decls_defs.get(v_ds), changed);
    }
  }
  def visit_1_3_0(anchor : T_Declarations, changed : AtomicBoolean) : Unit = anchor match {
    case p_scope(v_self,v_ds) => {
      a_decls_errs.set(v_self,a_decls_errs.get(v_ds));
    }
  }
  def visit_1_1_1(anchor : T_Declarations, changed : AtomicBoolean) : Unit = anchor match {
    case p_decls_empty(v_self) => {
    }
  }
  def visit_1_2_1(anchor : T_Declarations, changed : AtomicBoolean) : Unit = anchor match {
    case p_decls_empty(v_self) => {
      a_decls_defs.set(v_self,t_DeclPairLattice.v_bottom, changed);
    }
  }
  def visit_1_3_1(anchor : T_Declarations, changed : AtomicBoolean) : Unit = anchor match {
    case p_decls_empty(v_self) => {
      a_decls_errs.set(v_self,t_Messages.v_none());
    }
  }
  def visit_1_1_2(anchor : T_Declarations, changed : AtomicBoolean) : Unit = anchor match {
    case p_decls_append(v_self,v_ds,v_d) => {

      visit_1_1(v_ds, changed);

      visit_0_1(v_d, changed);
    }
  }
  def visit_1_2_2(anchor : T_Declarations, changed : AtomicBoolean) : Unit = anchor match {
    case p_decls_append(v_self,v_ds,v_d) => {
      a_decl_env.set(v_d,a_decls_env.get(v_self), changed);

      visit_0_2(v_d, changed);
      a_decls_env.set(v_ds,a_decls_env.get(v_self), changed);

      visit_1_2(v_ds, changed);
      val node = t_DeclPairLattice.v_select(a_decls_defs.get(v_ds),
        a_decl_name.get(v_d));
      node match {
        case t_DeclPairLattice.p_table_entry(_,v_0,v_value) => {
          a_decls_defs.set(v_self,a_decls_defs.get(v_ds), changed);
        }
        case _ => {
          a_decls_defs.set(v_self,t_DeclPairLattice.v_join(a_decls_defs.get(v_ds),
            a_decl_pair.get(v_d)), changed);
        }}
    }
  }
  def visit_1_3_2(anchor : T_Declarations, changed : AtomicBoolean) : Unit = anchor match {
    case p_decls_append(v_self,v_ds,v_d) => {
      {
        val newChanged = new AtomicBoolean(false);
        do {
          newChanged.set(false);
          val node = t_DeclPairLattice.v_select(a_decls_defs.get(v_ds),
            a_decl_name.get(v_d));
          node match {
            case t_DeclPairLattice.p_table_entry(_,v_0,v_value) => {

              visit_1_3(v_ds, newChanged);

              visit_0_3(v_d, newChanged);
              a_decls_errs.set(v_self,new M__basic_19[ T_String,T_Messages](t_String,t_Messages).v__op_5w(new M__basic_19[ T_String,T_Messages](t_String,t_Messages).v__op_5w(t_Messages.v_single(new M__basic_18[ T_String](t_String).v__op_ss("identifier ",
                new M__basic_18[ T_String](t_String).v__op_ss(v_symbol_name(a_decl_name.get(v_d)),
                  " is multiply defined"))),
                a_decls_errs.get(v_ds)),
                a_decl_errs.get(v_d)));
            }
            case _ => {

              visit_1_3(v_ds, newChanged);

              visit_0_3(v_d, newChanged);
              a_decls_errs.set(v_self,new M__basic_19[ T_String,T_Messages](t_String,t_Messages).v__op_5w(a_decls_errs.get(v_ds),
                a_decl_errs.get(v_d)));
            }}

        } while(newChanged.get);
      }
    }
  }
  def visit_1_1_3(anchor : T_Declarations, changed : AtomicBoolean) : Unit = anchor match {
    case p_decls_append_scope(v_self,v_ds,v_inner) => {

      visit_1_1(v_ds, changed);

      visit_1_1(v_inner, changed);
      {
        val newChanged = new AtomicBoolean(false);
        do {
          newChanged.set(false);
          a_decls_env.set(v_inner,a_decls_defs.get(v_inner), newChanged);

          visit_1_2(v_inner, newChanged);

        } while(newChanged.get);
      }

      visit_1_3(v_inner, changed);
    }
  }
  def visit_1_2_3(anchor : T_Declarations, changed : AtomicBoolean) : Unit = anchor match {
    case p_decls_append_scope(v_self,v_ds,v_inner) => {
      a_decls_env.set(v_ds,a_decls_env.get(v_self), changed);

      visit_1_2(v_ds, changed);
      a_decls_defs.set(v_self,t_DeclPairLattice.v_join(a_decls_defs.get(v_ds),
        a_decls_defs.get(v_inner)), changed);
    }
  }
  def visit_1_3_3(anchor : T_Declarations, changed : AtomicBoolean) : Unit = anchor match {
    case p_decls_append_scope(v_self,v_ds,v_inner) => {

      visit_1_3(v_ds, changed);
      a_decls_errs.set(v_self,new M__basic_19[ T_String,T_Messages](t_String,t_Messages).v__op_5w(a_decls_errs.get(v_ds),
        a_decls_errs.get(v_inner)));
    }
  }

  def visit_2_1(node : T_Expression, changed : AtomicBoolean) : Unit = node match {
    case p_expr_term(_,_) => visit_2_1_0(node, changed);
    case p_expr_apply(_,_,_,_) => visit_2_1_1(node, changed);
  };
  def visit_2_2(node : T_Expression, changed : AtomicBoolean) : Unit = node match {
    case p_expr_term(_,_) => visit_2_2_0(node, changed);
    case p_expr_apply(_,_,_,_) => visit_2_2_1(node, changed);
  };
  def visit_2_3(node : T_Expression, changed : AtomicBoolean) : Unit = node match {
    case p_expr_term(_,_) => visit_2_3_0(node, changed);
    case p_expr_apply(_,_,_,_) => visit_2_3_1(node, changed);
  };
  def visit_2_1_0(anchor : T_Expression, changed : AtomicBoolean) : Unit = anchor match {
    case p_expr_term(v_self,v_t) => {

      visit_3_1(v_t, changed);
    }
  }
  def visit_2_2_0(anchor : T_Expression, changed : AtomicBoolean) : Unit = anchor match {
    case p_expr_term(v_self,v_t) => {
      a_term_env.set(v_t,a_expr_env.get(v_self), changed);

      visit_3_2(v_t, changed);
      a_expr_val.set(v_self,a_term_val.get(v_t), changed);
    }
  }
  def visit_2_3_0(anchor : T_Expression, changed : AtomicBoolean) : Unit = anchor match {
    case p_expr_term(v_self,v_t) => {

      visit_3_3(v_t, changed);
      a_expr_errs.set(v_self,a_term_errs.get(v_t));
    }
  }
  def visit_2_1_1(anchor : T_Expression, changed : AtomicBoolean) : Unit = anchor match {
    case p_expr_apply(v_self,v_e,v_op,v_t) => {

      visit_2_1(v_e, changed);

      visit_4_1(v_op, changed);

      visit_3_1(v_t, changed);
    }
  }
  def visit_2_2_1(anchor : T_Expression, changed : AtomicBoolean) : Unit = anchor match {
    case p_expr_apply(v_self,v_e,v_op,v_t) => {
      a_term_env.set(v_t,a_expr_env.get(v_self), changed);

      visit_3_2(v_t, changed);
      a_expr_env.set(v_e,a_expr_env.get(v_self), changed);

      visit_2_2(v_e, changed);
      a_op_rval.set(v_op,a_term_val.get(v_t), changed);
      a_op_lval.set(v_op,a_expr_val.get(v_e), changed);

      visit_4_2(v_op, changed);
      a_expr_val.set(v_self,a_op_val.get(v_op), changed);
    }
  }
  def visit_2_3_1(anchor : T_Expression, changed : AtomicBoolean) : Unit = anchor match {
    case p_expr_apply(v_self,v_e,v_op,v_t) => {

      visit_2_3(v_e, changed);

      visit_4_3(v_op, changed);

      visit_3_3(v_t, changed);
      a_expr_errs.set(v_self,new M__basic_19[ T_String,T_Messages](t_String,t_Messages).v__op_5w(a_expr_errs.get(v_e),
        a_term_errs.get(v_t)));
    }
  }

  def visit_3_1(node : T_Term, changed : AtomicBoolean) : Unit = node match {
    case p_term_variable(_,_) => visit_3_1_0(node, changed);
    case p_term_literal(_,_) => visit_3_1_1(node, changed);
  };
  def visit_3_2(node : T_Term, changed : AtomicBoolean) : Unit = node match {
    case p_term_variable(_,_) => visit_3_2_0(node, changed);
    case p_term_literal(_,_) => visit_3_2_1(node, changed);
  };
  def visit_3_3(node : T_Term, changed : AtomicBoolean) : Unit = node match {
    case p_term_variable(_,_) => visit_3_3_0(node, changed);
    case p_term_literal(_,_) => visit_3_3_1(node, changed);
  };
  def visit_3_1_0(anchor : T_Term, changed : AtomicBoolean) : Unit = anchor match {
    case p_term_variable(v_self,v_s) => {
    }
  }
  def visit_3_2_0(anchor : T_Term, changed : AtomicBoolean) : Unit = anchor match {
    case p_term_variable(v_self,v_s) => {
      val node = t_DeclPairLattice.v_select(a_term_env.get(v_self),
        v_s);
      node match {
        case t_DeclPairLattice.p_table_entry(_,v_0,v_value) => {
          a1_variable_value.set(anchor,v_value, changed);
          a_term_val.set(v_self,a1_variable_value.get(anchor), changed);
        }
        case _ => {
          a1_variable_value.set(anchor,t_IntegerLattice.v_bottom, changed);
          a_term_val.set(v_self,a1_variable_value.get(anchor), changed);
        }}
    }
  }
  def visit_3_3_0(anchor : T_Term, changed : AtomicBoolean) : Unit = anchor match {
    case p_term_variable(v_self,v_s) => {
      {
        val newChanged = new AtomicBoolean(false);
        do {
          newChanged.set(false);
          val node = t_DeclPairLattice.v_select(a_term_env.get(v_self),
            v_s);
          node match {
            case t_DeclPairLattice.p_table_entry(_,v_0,v_value) => {
              if (new M__basic_2[ T_IntegerLattice](t_IntegerLattice).v__op_0(a1_variable_value.get(anchor),
                t_IntegerLattice.v_bottom)) {
                a2_variable_defined.set(anchor,v_true, newChanged);
                if (a2_variable_defined.get(anchor)) {
                  a_term_errs.set(v_self,t_Messages.v_single(new M__basic_18[ T_String](t_String).v__op_ss("identifier ",
                    new M__basic_18[ T_String](t_String).v__op_ss(v_symbol_name(v_s),
                      " is defined but has an unknown value"))));
                } else {
                  a_term_errs.set(v_self,t_Messages.v_single(new M__basic_18[ T_String](t_String).v__op_ss("unknown identifier of ",
                    v_symbol_name(v_s))));
                }
              } else {
                a2_variable_defined.set(anchor,v_true, newChanged);
                a_term_errs.set(v_self,t_Messages.v_none());
              }
            }
            case _ => {
              if (new M__basic_2[ T_IntegerLattice](t_IntegerLattice).v__op_0(a1_variable_value.get(anchor),
                t_IntegerLattice.v_bottom)) {
                a2_variable_defined.set(anchor,v_false, newChanged);
                if (a2_variable_defined.get(anchor)) {
                  a_term_errs.set(v_self,t_Messages.v_single(new M__basic_18[ T_String](t_String).v__op_ss("identifier ",
                    new M__basic_18[ T_String](t_String).v__op_ss(v_symbol_name(v_s),
                      " is defined but has an unknown value"))));
                } else {
                  a_term_errs.set(v_self,t_Messages.v_single(new M__basic_18[ T_String](t_String).v__op_ss("unknown identifier of ",
                    v_symbol_name(v_s))));
                }
              } else {
                a2_variable_defined.set(anchor,v_false, newChanged);
                a_term_errs.set(v_self,t_Messages.v_none());
              }
            }}

        } while(newChanged.get);
      }
    }
  }
  def visit_3_1_1(anchor : T_Term, changed : AtomicBoolean) : Unit = anchor match {
    case p_term_literal(v_self,v_i) => {
    }
  }
  def visit_3_2_1(anchor : T_Term, changed : AtomicBoolean) : Unit = anchor match {
    case p_term_literal(v_self,v_i) => {
      a_term_val.set(v_self,t_IntegerLattice.v_lift(v_i), changed);
    }
  }
  def visit_3_3_1(anchor : T_Term, changed : AtomicBoolean) : Unit = anchor match {
    case p_term_literal(v_self,v_i) => {
      a_term_errs.set(v_self,t_Messages.v_none());
    }
  }

  def visit_4_1(node : T_Operation, changed : AtomicBoolean) : Unit = node match {
    case p_op_add(_) => visit_4_1_0(node, changed);
    case p_op_mul(_) => visit_4_1_1(node, changed);
    case p_op_sub(_) => visit_4_1_2(node, changed);
    case p_op_div(_) => visit_4_1_3(node, changed);
  };
  def visit_4_2(node : T_Operation, changed : AtomicBoolean) : Unit = node match {
    case p_op_add(_) => visit_4_2_0(node, changed);
    case p_op_mul(_) => visit_4_2_1(node, changed);
    case p_op_sub(_) => visit_4_2_2(node, changed);
    case p_op_div(_) => visit_4_2_3(node, changed);
  };
  def visit_4_3(node : T_Operation, changed : AtomicBoolean) : Unit = node match {
    case p_op_add(_) => visit_4_3_0(node, changed);
    case p_op_mul(_) => visit_4_3_1(node, changed);
    case p_op_sub(_) => visit_4_3_2(node, changed);
    case p_op_div(_) => visit_4_3_3(node, changed);
  };
  def visit_4_1_0(anchor : T_Operation, changed : AtomicBoolean) : Unit = anchor match {
    case p_op_add(v_self) => {
    }
  }
  def visit_4_2_0(anchor : T_Operation, changed : AtomicBoolean) : Unit = anchor match {
    case p_op_add(v_self) => {
      if (v_or(new M__basic_2[ T_IntegerLattice](t_IntegerLattice).v__op_0(a_op_lval.get(v_self),
        t_IntegerLattice.v_bottom),
        new M__basic_2[ T_IntegerLattice](t_IntegerLattice).v__op_0(a_op_rval.get(v_self),
          t_IntegerLattice.v_bottom))) {
        a_op_val.set(v_self,t_IntegerLattice.v_bottom, changed);
      } else {
        a_op_val.set(v_self,t_IntegerLattice.v_applyf2(t_Integer.v_plus,
          a_op_lval.get(v_self),
          a_op_rval.get(v_self)), changed);
      }
    }
  }
  def visit_4_3_0(anchor : T_Operation, changed : AtomicBoolean) : Unit = anchor match {
    case p_op_add(v_self) => {
      {
        val newChanged = new AtomicBoolean(false);
        do {
          newChanged.set(false);
          if (v_or(new M__basic_2[ T_IntegerLattice](t_IntegerLattice).v__op_0(a_op_lval.get(v_self),
            t_IntegerLattice.v_bottom),
            new M__basic_2[ T_IntegerLattice](t_IntegerLattice).v__op_0(a_op_rval.get(v_self),
              t_IntegerLattice.v_bottom))) {
          } else {
          }

        } while(newChanged.get);
      }
    }
  }
  def visit_4_1_1(anchor : T_Operation, changed : AtomicBoolean) : Unit = anchor match {
    case p_op_mul(v_self) => {
    }
  }
  def visit_4_2_1(anchor : T_Operation, changed : AtomicBoolean) : Unit = anchor match {
    case p_op_mul(v_self) => {
      if (v_or(new M__basic_2[ T_IntegerLattice](t_IntegerLattice).v__op_0(a_op_lval.get(v_self),
        t_IntegerLattice.v_bottom),
        new M__basic_2[ T_IntegerLattice](t_IntegerLattice).v__op_0(a_op_rval.get(v_self),
          t_IntegerLattice.v_bottom))) {
        a_op_val.set(v_self,t_IntegerLattice.v_bottom, changed);
      } else {
        a_op_val.set(v_self,t_IntegerLattice.v_applyf2(t_Integer.v_times,
          a_op_lval.get(v_self),
          a_op_rval.get(v_self)), changed);
      }
    }
  }
  def visit_4_3_1(anchor : T_Operation, changed : AtomicBoolean) : Unit = anchor match {
    case p_op_mul(v_self) => {
      {
        val newChanged = new AtomicBoolean(false);
        do {
          newChanged.set(false);
          if (v_or(new M__basic_2[ T_IntegerLattice](t_IntegerLattice).v__op_0(a_op_lval.get(v_self),
            t_IntegerLattice.v_bottom),
            new M__basic_2[ T_IntegerLattice](t_IntegerLattice).v__op_0(a_op_rval.get(v_self),
              t_IntegerLattice.v_bottom))) {
          } else {
          }

        } while(newChanged.get);
      }
    }
  }
  def visit_4_1_2(anchor : T_Operation, changed : AtomicBoolean) : Unit = anchor match {
    case p_op_sub(v_self) => {
    }
  }
  def visit_4_2_2(anchor : T_Operation, changed : AtomicBoolean) : Unit = anchor match {
    case p_op_sub(v_self) => {
      if (v_or(new M__basic_2[ T_IntegerLattice](t_IntegerLattice).v__op_0(a_op_lval.get(v_self),
        t_IntegerLattice.v_bottom),
        new M__basic_2[ T_IntegerLattice](t_IntegerLattice).v__op_0(a_op_rval.get(v_self),
          t_IntegerLattice.v_bottom))) {
        a_op_val.set(v_self,t_IntegerLattice.v_bottom, changed);
      } else {
        a_op_val.set(v_self,t_IntegerLattice.v_applyf2(t_Integer.v_minus,
          a_op_lval.get(v_self),
          a_op_rval.get(v_self)), changed);
      }
    }
  }
  def visit_4_3_2(anchor : T_Operation, changed : AtomicBoolean) : Unit = anchor match {
    case p_op_sub(v_self) => {
      {
        val newChanged = new AtomicBoolean(false);
        do {
          newChanged.set(false);
          if (v_or(new M__basic_2[ T_IntegerLattice](t_IntegerLattice).v__op_0(a_op_lval.get(v_self),
            t_IntegerLattice.v_bottom),
            new M__basic_2[ T_IntegerLattice](t_IntegerLattice).v__op_0(a_op_rval.get(v_self),
              t_IntegerLattice.v_bottom))) {
          } else {
          }

        } while(newChanged.get);
      }
    }
  }
  def visit_4_1_3(anchor : T_Operation, changed : AtomicBoolean) : Unit = anchor match {
    case p_op_div(v_self) => {
    }
  }
  def visit_4_2_3(anchor : T_Operation, changed : AtomicBoolean) : Unit = anchor match {
    case p_op_div(v_self) => {
      if (v_or(new M__basic_2[ T_IntegerLattice](t_IntegerLattice).v__op_0(a_op_lval.get(v_self),
        t_IntegerLattice.v_bottom),
        new M__basic_2[ T_IntegerLattice](t_IntegerLattice).v__op_0(a_op_rval.get(v_self),
          t_IntegerLattice.v_bottom))) {
        a_op_val.set(v_self,t_IntegerLattice.v_bottom, changed);
      } else {
        a_op_val.set(v_self,t_IntegerLattice.v_applyf2(t_Integer.v_divide,
          a_op_lval.get(v_self),
          a_op_rval.get(v_self)), changed);
      }
    }
  }
  def visit_4_3_3(anchor : T_Operation, changed : AtomicBoolean) : Unit = anchor match {
    case p_op_div(v_self) => {
      {
        val newChanged = new AtomicBoolean(false);
        do {
          newChanged.set(false);
          if (v_or(new M__basic_2[ T_IntegerLattice](t_IntegerLattice).v__op_0(a_op_lval.get(v_self),
            t_IntegerLattice.v_bottom),
            new M__basic_2[ T_IntegerLattice](t_IntegerLattice).v__op_0(a_op_rval.get(v_self),
              t_IntegerLattice.v_bottom))) {
          } else {
          }

        } while(newChanged.get);
      }
    }
  }

  def visit_5_1(node : T_Program, changed : AtomicBoolean) : Unit = node match {
    case p_program(_,_) => visit_5_1_0(node, changed);
  };
  def visit_5_1_0(anchor : T_Program, changed : AtomicBoolean) : Unit = anchor match {
    case p_program(v_self,v_ds) => {

      visit_1_1(v_ds, changed);
      {
        val newChanged = new AtomicBoolean(false);
        do {
          newChanged.set(false);
          a_decls_env.set(v_ds,t_DeclPairLattice.v_bottom, newChanged);

          visit_1_2(v_ds, newChanged);

        } while(newChanged.get);
      }

      visit_1_3(v_ds, changed);
      a_program_errs.set(v_self,a_decls_errs.get(v_ds));
    }
  }

  def visit() : Unit = {
    val roots = t_Program.nodes;
    for (root <- roots) {
      visit_5_1(root, new AtomicBoolean(false));
    }
  }
  override def finish() : Unit = {
    visit();
    t_IntegerLattice.finish();
    t_DeclPairLattice.finish();
    t_Messages.finish();
    super.finish();
  }
}

