// Generated by aps2scala version 0.3.6
import basic_implicit._;
object farrow_ubd_tree_implicit {
  val farrow_ubd_tree_loaded = true;
  import symbol_implicit._;
  import table_implicit._;
}
import farrow_ubd_tree_implicit._;

import symbol_implicit._;
import table_implicit._;
trait C_FARROW_UBD_TREE[T_Result] extends C_TYPE[T_Result] {
  type T_Declaration <: Node;
  val t_Declaration : C_PHYLUM[T_Declaration];
  type T_Declarations <: Node;
  val t_Declarations : C_PHYLUM[T_Declarations];
  type T_Expression <: Node;
  val t_Expression : C_PHYLUM[T_Expression];
  type T_Term <: Node;
  val t_Term : C_PHYLUM[T_Term];
  type T_Operation <: Node;
  val t_Operation : C_PHYLUM[T_Operation];
  type T_Program <: Node;
  val t_Program : C_PHYLUM[T_Program];
  val p_scope : PatternFunction[(T_Declarations,T_Declarations)];
  def v_scope : (T_Declarations) => T_Declarations;
  val p_decl_assign : PatternFunction[(T_Declaration,T_Symbol,T_Expression)];
  def v_decl_assign : (T_Symbol,T_Expression) => T_Declaration;
  val p_decls_empty : PatternFunction[(T_Declarations)];
  def v_decls_empty : () => T_Declarations;
  val p_decls_append : PatternFunction[(T_Declarations,T_Declarations,T_Declaration)];
  def v_decls_append : (T_Declarations,T_Declaration) => T_Declarations;
  val p_decls_append_scope : PatternFunction[(T_Declarations,T_Declarations,T_Declarations)];
  def v_decls_append_scope : (T_Declarations,T_Declarations) => T_Declarations;
  val p_expr_term : PatternFunction[(T_Expression,T_Term)];
  def v_expr_term : (T_Term) => T_Expression;
  val p_op_add : PatternFunction[(T_Operation)];
  def v_op_add : () => T_Operation;
  val p_op_mul : PatternFunction[(T_Operation)];
  def v_op_mul : () => T_Operation;
  val p_op_sub : PatternFunction[(T_Operation)];
  def v_op_sub : () => T_Operation;
  val p_op_div : PatternFunction[(T_Operation)];
  def v_op_div : () => T_Operation;
  val p_expr_apply : PatternFunction[(T_Expression,T_Expression,T_Operation,T_Term)];
  def v_expr_apply : (T_Expression,T_Operation,T_Term) => T_Expression;
  val p_term_variable : PatternFunction[(T_Term,T_Symbol)];
  def v_term_variable : (T_Symbol) => T_Term;
  val p_term_literal : PatternFunction[(T_Term,T_Integer)];
  def v_term_literal : (T_Integer) => T_Term;
  val p_program : PatternFunction[(T_Program,T_Declarations)];
  def v_program : (T_Declarations) => T_Program;
}

abstract class T_FARROW_UBD_TREE(t : C_FARROW_UBD_TREE[T_FARROW_UBD_TREE]) extends Value(t) { }

class M_FARROW_UBD_TREE(name : String)
  extends I_TYPE[T_FARROW_UBD_TREE](name)
    with C_FARROW_UBD_TREE[T_FARROW_UBD_TREE]
{
  val t_Result : this.type = this;
  abstract class T_Declaration(t : I_PHYLUM[T_Declaration]) extends Node(t) {}
  val t_Declaration = new I_PHYLUM[T_Declaration]("Declaration");

  abstract class T_Declarations(t : I_PHYLUM[T_Declarations]) extends Node(t) {}
  val t_Declarations = new I_PHYLUM[T_Declarations]("Declarations");

  abstract class T_Expression(t : I_PHYLUM[T_Expression]) extends Node(t) {}
  val t_Expression = new I_PHYLUM[T_Expression]("Expression");

  abstract class T_Term(t : I_PHYLUM[T_Term]) extends Node(t) {}
  val t_Term = new I_PHYLUM[T_Term]("Term");

  abstract class T_Operation(t : I_PHYLUM[T_Operation]) extends Node(t) {}
  val t_Operation = new I_PHYLUM[T_Operation]("Operation");

  abstract class T_Program(t : I_PHYLUM[T_Program]) extends Node(t) {
    override def isRooted : Boolean = true;
  }
  val t_Program = new I_PHYLUM[T_Program]("Program");

  case class c_scope(v_ds : T_Declarations) extends T_Declarations(t_Declarations) {
    override def children : List[Node] = List(v_ds);
    override def toString() : String = Debug.with_level {
      "scope("+ v_ds+ ")";
    }
  }
  def u_scope(x:Any) : Option[(T_Declarations,T_Declarations)] = x match {
    case x@c_scope(v_ds) => Some((x,v_ds));
    case _ => None };
  val v_scope = f_scope _;
  def f_scope(v_ds : T_Declarations):T_Declarations = c_scope(v_ds).register;
  val p_scope = new PatternFunction[(T_Declarations,T_Declarations)](u_scope);

  case class c_decl_assign(v_s : T_Symbol,v_e : T_Expression) extends T_Declaration(t_Declaration) {
    override def children : List[Node] = List(v_e);
    override def toString() : String = Debug.with_level {
      "decl_assign("+ v_s + ","+ v_e+ ")";
    }
  }
  def u_decl_assign(x:Any) : Option[(T_Declaration,T_Symbol,T_Expression)] = x match {
    case x@c_decl_assign(v_s,v_e) => Some((x,v_s,v_e));
    case _ => None };
  val v_decl_assign = f_decl_assign _;
  def f_decl_assign(v_s : T_Symbol, v_e : T_Expression):T_Declaration = c_decl_assign(v_s,v_e).register;
  val p_decl_assign = new PatternFunction[(T_Declaration,T_Symbol,T_Expression)](u_decl_assign);

  case class c_decls_empty() extends T_Declarations(t_Declarations) {
    override def children : List[Node] = List();
    override def toString() : String = Debug.with_level {
      "decls_empty("+ ")";
    }
  }
  def u_decls_empty(x:Any) : Option[(T_Declarations)] = x match {
    case x@c_decls_empty() => Some(x);
    case _ => None };
  val v_decls_empty = f_decls_empty _;
  def f_decls_empty():T_Declarations = c_decls_empty().register;
  val p_decls_empty = new PatternFunction[(T_Declarations)](u_decls_empty);

  case class c_decls_append(v_ds : T_Declarations,v_d : T_Declaration) extends T_Declarations(t_Declarations) {
    override def children : List[Node] = List(v_ds,v_d);
    override def toString() : String = Debug.with_level {
      "decls_append("+ v_ds + ","+ v_d+ ")";
    }
  }
  def u_decls_append(x:Any) : Option[(T_Declarations,T_Declarations,T_Declaration)] = x match {
    case x@c_decls_append(v_ds,v_d) => Some((x,v_ds,v_d));
    case _ => None };
  val v_decls_append = f_decls_append _;
  def f_decls_append(v_ds : T_Declarations, v_d : T_Declaration):T_Declarations = c_decls_append(v_ds,v_d).register;
  val p_decls_append = new PatternFunction[(T_Declarations,T_Declarations,T_Declaration)](u_decls_append);

  case class c_decls_append_scope(v_ds : T_Declarations,v_inner : T_Declarations) extends T_Declarations(t_Declarations) {
    override def children : List[Node] = List(v_ds,v_inner);
    override def toString() : String = Debug.with_level {
      "decls_append_scope("+ v_ds + ","+ v_inner+ ")";
    }
  }
  def u_decls_append_scope(x:Any) : Option[(T_Declarations,T_Declarations,T_Declarations)] = x match {
    case x@c_decls_append_scope(v_ds,v_inner) => Some((x,v_ds,v_inner));
    case _ => None };
  val v_decls_append_scope = f_decls_append_scope _;
  def f_decls_append_scope(v_ds : T_Declarations, v_inner : T_Declarations):T_Declarations = c_decls_append_scope(v_ds,v_inner).register;
  val p_decls_append_scope = new PatternFunction[(T_Declarations,T_Declarations,T_Declarations)](u_decls_append_scope);

  case class c_expr_term(v_t : T_Term) extends T_Expression(t_Expression) {
    override def children : List[Node] = List(v_t);
    override def toString() : String = Debug.with_level {
      "expr_term("+ v_t+ ")";
    }
  }
  def u_expr_term(x:Any) : Option[(T_Expression,T_Term)] = x match {
    case x@c_expr_term(v_t) => Some((x,v_t));
    case _ => None };
  val v_expr_term = f_expr_term _;
  def f_expr_term(v_t : T_Term):T_Expression = c_expr_term(v_t).register;
  val p_expr_term = new PatternFunction[(T_Expression,T_Term)](u_expr_term);

  case class c_op_add() extends T_Operation(t_Operation) {
    override def children : List[Node] = List();
    override def toString() : String = Debug.with_level {
      "op_add("+ ")";
    }
  }
  def u_op_add(x:Any) : Option[(T_Operation)] = x match {
    case x@c_op_add() => Some(x);
    case _ => None };
  val v_op_add = f_op_add _;
  def f_op_add():T_Operation = c_op_add().register;
  val p_op_add = new PatternFunction[(T_Operation)](u_op_add);

  case class c_op_mul() extends T_Operation(t_Operation) {
    override def children : List[Node] = List();
    override def toString() : String = Debug.with_level {
      "op_mul("+ ")";
    }
  }
  def u_op_mul(x:Any) : Option[(T_Operation)] = x match {
    case x@c_op_mul() => Some(x);
    case _ => None };
  val v_op_mul = f_op_mul _;
  def f_op_mul():T_Operation = c_op_mul().register;
  val p_op_mul = new PatternFunction[(T_Operation)](u_op_mul);

  case class c_op_sub() extends T_Operation(t_Operation) {
    override def children : List[Node] = List();
    override def toString() : String = Debug.with_level {
      "op_sub("+ ")";
    }
  }
  def u_op_sub(x:Any) : Option[(T_Operation)] = x match {
    case x@c_op_sub() => Some(x);
    case _ => None };
  val v_op_sub = f_op_sub _;
  def f_op_sub():T_Operation = c_op_sub().register;
  val p_op_sub = new PatternFunction[(T_Operation)](u_op_sub);

  case class c_op_div() extends T_Operation(t_Operation) {
    override def children : List[Node] = List();
    override def toString() : String = Debug.with_level {
      "op_div("+ ")";
    }
  }
  def u_op_div(x:Any) : Option[(T_Operation)] = x match {
    case x@c_op_div() => Some(x);
    case _ => None };
  val v_op_div = f_op_div _;
  def f_op_div():T_Operation = c_op_div().register;
  val p_op_div = new PatternFunction[(T_Operation)](u_op_div);

  case class c_expr_apply(v_e : T_Expression,v_op : T_Operation,v_t : T_Term) extends T_Expression(t_Expression) {
    override def children : List[Node] = List(v_e,v_op,v_t);
    override def toString() : String = Debug.with_level {
      "expr_apply("+ v_e + ","+ v_op + ","+ v_t+ ")";
    }
  }
  def u_expr_apply(x:Any) : Option[(T_Expression,T_Expression,T_Operation,T_Term)] = x match {
    case x@c_expr_apply(v_e,v_op,v_t) => Some((x,v_e,v_op,v_t));
    case _ => None };
  val v_expr_apply = f_expr_apply _;
  def f_expr_apply(v_e : T_Expression, v_op : T_Operation, v_t : T_Term):T_Expression = c_expr_apply(v_e,v_op,v_t).register;
  val p_expr_apply = new PatternFunction[(T_Expression,T_Expression,T_Operation,T_Term)](u_expr_apply);

  case class c_term_variable(v_s : T_Symbol) extends T_Term(t_Term) {
    override def children : List[Node] = List();
    override def toString() : String = Debug.with_level {
      "term_variable("+ v_s+ ")";
    }
  }
  def u_term_variable(x:Any) : Option[(T_Term,T_Symbol)] = x match {
    case x@c_term_variable(v_s) => Some((x,v_s));
    case _ => None };
  val v_term_variable = f_term_variable _;
  def f_term_variable(v_s : T_Symbol):T_Term = c_term_variable(v_s).register;
  val p_term_variable = new PatternFunction[(T_Term,T_Symbol)](u_term_variable);

  case class c_term_literal(v_i : T_Integer) extends T_Term(t_Term) {
    override def children : List[Node] = List();
    override def toString() : String = Debug.with_level {
      "term_literal("+ v_i+ ")";
    }
  }
  def u_term_literal(x:Any) : Option[(T_Term,T_Integer)] = x match {
    case x@c_term_literal(v_i) => Some((x,v_i));
    case _ => None };
  val v_term_literal = f_term_literal _;
  def f_term_literal(v_i : T_Integer):T_Term = c_term_literal(v_i).register;
  val p_term_literal = new PatternFunction[(T_Term,T_Integer)](u_term_literal);

  case class c_program(v_ds : T_Declarations) extends T_Program(t_Program) {
    override def children : List[Node] = List(v_ds);
    override def toString() : String = Debug.with_level {
      "program("+ v_ds+ ")";
    }
  }
  def u_program(x:Any) : Option[(T_Program,T_Declarations)] = x match {
    case x@c_program(v_ds) => Some((x,v_ds));
    case _ => None };
  val v_program = f_program _;
  def f_program(v_ds : T_Declarations):T_Program = c_program(v_ds).register;
  val p_program = new PatternFunction[(T_Program,T_Declarations)](u_program);

  override def finish() : Unit = {
    super.finish();
  }

}

