/* Generated by Scala-Bison version 1.1 */

object FarrowUbdTokens {
  class YYSymbol;

  class YYToken extends YYSymbol;

  case class YYCHAR(yy: Char) extends YYToken {
    override def toString() : String = "'" + yy + "'";
  }
  case class YYEOF() extends YYToken;
  case class ID(yy: Symbol) extends YYToken;
  case class LITERAL(yy: Symbol) extends YYToken;
  case class SEMICOLON() extends YYToken;
  case class EQ() extends YYToken;
  case class OPN_BRACE() extends YYToken;
  case class CLS_BRACE() extends YYToken;
  case class PLUS() extends YYToken;
  case class MINUS() extends YYToken;
  case class MUL() extends YYToken;
  case class DIV() extends YYToken;
}
