/* Generated by Scala-Bison version 1.1 */

/** Generated LALR(1) recursive-ascent-descent parser */
class FarrowUbdParser extends FarrowUbdParserBase {
  class YYNonterminal extends FarrowUbdTokens.YYSymbol;

  case class YYNTerror(yy : String) extends YYNonterminal;
  case class YYNTdecl(yy: Declaration) extends YYNonterminal;
  case class YYNTdecls(yy: Declarations) extends YYNonterminal;
  case class YYNTexpr(yy: Expression) extends YYNonterminal;
  case class YYNTterm(yy: Term) extends YYNonterminal;
  case class YYNTop(yy: Operation) extends YYNonterminal;
  case class YYNTprogram(yy: Program) extends YYNonterminal;

  private var yynt : YYNonterminal = null;

  case class YYError(s:String) extends Exception(s);

  // boilerplate

  var yydebug : Boolean = false;
  private var yyinput : Iterator[FarrowUbdTokens.YYToken] = null;
  private var yycur : FarrowUbdTokens.YYToken = null;

  private def yynext() = {
    yycur = {
      if (yyinput.hasNext) {
        yyinput.next
      } else {
        FarrowUbdTokens.YYEOF();
      }
    }
  }

  private def yypanic(test : (FarrowUbdTokens.YYToken) => Boolean) = {
    while (!test(yycur)) {
      yynext;
      if (yycur == FarrowUbdTokens.YYEOF()) throw new YYError("Giving up")
    }
  }

  def yyreset(input : Iterator[FarrowUbdTokens.YYToken]) = {
    yyinput = input;
    yynt = null;
    yynext
  }

  def yyparse() : Boolean = {
    try {
      parse_program()
      parse_YYEOF()
      true
    } catch {
      case YYError(s) => yyerror(s); false
    }
  }

  def parse_YYCHAR(yy:Char) : Unit = {
    yycur match {
      case FarrowUbdTokens.YYCHAR(`yy`) => yynext; ()
      case _ => throw new YYError("Expected '"+yy+"'");
    }
  }

  // generated parser

  def parse_YYEOF() : Unit = {
    yycur match {
      case FarrowUbdTokens.YYEOF() => yynext; ()
      case _ => throw new YYError("Expected 'YYEOF'");
    }
  }

  def parse_ID() : Symbol = {
    yycur match {
      case FarrowUbdTokens.ID(yy) => yynext; yy
      case _ => throw new YYError("Expected 'ID'");
    }
  }

  def parse_LITERAL() : Symbol = {
    yycur match {
      case FarrowUbdTokens.LITERAL(yy) => yynext; yy
      case _ => throw new YYError("Expected 'LITERAL'");
    }
  }

  def parse_SEMICOLON() : Unit = {
    yycur match {
      case FarrowUbdTokens.SEMICOLON() => yynext; ()
      case _ => throw new YYError("Expected 'SEMICOLON'");
    }
  }

  def parse_EQ() : Unit = {
    yycur match {
      case FarrowUbdTokens.EQ() => yynext; ()
      case _ => throw new YYError("Expected 'EQ'");
    }
  }

  def parse_OPN_BRACE() : Unit = {
    yycur match {
      case FarrowUbdTokens.OPN_BRACE() => yynext; ()
      case _ => throw new YYError("Expected 'OPN_BRACE'");
    }
  }

  def parse_CLS_BRACE() : Unit = {
    yycur match {
      case FarrowUbdTokens.CLS_BRACE() => yynext; ()
      case _ => throw new YYError("Expected 'CLS_BRACE'");
    }
  }

  def parse_PLUS() : Unit = {
    yycur match {
      case FarrowUbdTokens.PLUS() => yynext; ()
      case _ => throw new YYError("Expected 'PLUS'");
    }
  }

  def parse_MINUS() : Unit = {
    yycur match {
      case FarrowUbdTokens.MINUS() => yynext; ()
      case _ => throw new YYError("Expected 'MINUS'");
    }
  }

  def parse_MUL() : Unit = {
    yycur match {
      case FarrowUbdTokens.MUL() => yynext; ()
      case _ => throw new YYError("Expected 'MUL'");
    }
  }

  def parse_DIV() : Unit = {
    yycur match {
      case FarrowUbdTokens.DIV() => yynext; ()
      case _ => throw new YYError("Expected 'DIV'");
    }
  }

  def parse_decls() : Declarations = {
    yystate2();
    yynt match {
      case YYNTdecls(yy) => yy
      case YYNTerror(s) => throw new YYError(s)
    }
  }

  def parse_decl() : Declaration = {
    yystate7();
    yynt match {
      case YYNTdecl(yy) => yy
      case YYNTerror(s) => throw new YYError(s)
    }
  }

  def parse_op() : Operation = {
    yystate15();
    yynt match {
      case YYNTop(yy) => yy
      case YYNTerror(s) => throw new YYError(s)
    }
  }

  def parse_term() : Term = {
    yystate13();
    yynt match {
      case YYNTterm(yy) => yy
      case YYNTerror(s) => throw new YYError(s)
    }
  }

  def parse_program() : Program = {
    yystate0();
    yynt match {
      case YYNTprogram(yy) => yy
      case YYNTerror(s) => throw new YYError(s)
    }
  }


  /** Recursive descent parser after recognition point
   * program: . decls
   */
  private def yyrule1() : Program = {
    var yyresult : Program = null;
    val yyarg1 : Declarations = parse_decls();
    { yyresult = program(scope(yyarg1)); }
    yyresult
  }

  /** Recursive descent parser after recognition point
   * decls: .
   */
  private def yyrule2() : Declarations = {
    var yyresult : Declarations = null;
    { yyresult = decls_empty(); }
    yyresult
  }

  /** Recursive descent parser after recognition point
   * decls: decls . decl
   */
  private def yyrule3(yyarg1 : Declarations) : Declarations = {
    var yyresult : Declarations = null;
    val yyarg2 : Declaration = parse_decl();
    { yyresult = decls_append(yyarg1, yyarg2); }
    yyresult
  }

  /** Recursive descent parser after recognition point
   * decls: decls OPN_BRACE decls CLS_BRACE .
   */
  private def yyrule4(yyarg1 : Declarations, yyarg3 : Declarations) : Declarations = {
    var yyresult : Declarations = null;
    { yyresult = decls_append_scope(yyarg1, yyarg3); }
    yyresult
  }

  /** Recursive descent parser after recognition point
   * decl: ID EQ expr SEMICOLON .
   */
  private def yyrule5(yyarg1 : Symbol, yyarg3 : Expression) : Declaration = {
    var yyresult : Declaration = null;
    { yyresult = decl_assign(yyarg1, yyarg3); }
    yyresult
  }

  /** Recursive descent parser after recognition point
   * term: . ID
   */
  private def yyrule6() : Term = {
    var yyresult : Term = null;
    val yyarg1 : Symbol = parse_ID();
    { yyresult = term_variable(yyarg1); }
    yyresult
  }

  /** Recursive descent parser after recognition point
   * term: . LITERAL
   */
  private def yyrule7() : Term = {
    var yyresult : Term = null;
    val yyarg1 : Symbol = parse_LITERAL();
    { yyresult = term_literal(yyarg1); }
    yyresult
  }

  /** Recursive descent parser after recognition point
   * expr: . term
   */
  private def yyrule8() : Expression = {
    var yyresult : Expression = null;
    val yyarg1 : Term = parse_term();
    { yyresult = expr_term(yyarg1); }
    yyresult
  }

  /** Recursive descent parser after recognition point
   * expr: expr . op term
   */
  private def yyrule9(yyarg1 : Expression) : Expression = {
    var yyresult : Expression = null;
    val yyarg2 : Operation = parse_op();
    val yyarg3 : Term = parse_term();
    { yyresult = expr_apply(yyarg1, yyarg2, yyarg3); }
    yyresult
  }

  /** Recursive descent parser after recognition point
   * op: PLUS .
   */
  private def yyrule10() : Operation = {
    var yyresult : Operation = null;
    { yyresult = op_add(); }
    yyresult
  }

  /** Recursive descent parser after recognition point
   * op: MINUS .
   */
  private def yyrule11() : Operation = {
    var yyresult : Operation = null;
    { yyresult = op_sub(); }
    yyresult
  }

  /** Recursive descent parser after recognition point
   * op: MUL .
   */
  private def yyrule12() : Operation = {
    var yyresult : Operation = null;
    { yyresult = op_mul(); }
    yyresult
  }

  /** Recursive descent parser after recognition point
   * op: DIV .
   */
  private def yyrule13() : Operation = {
    var yyresult : Operation = null;
    { yyresult = op_div(); }
    yyresult
  }

  private def yystate6(yyarg1: Declarations, yyarg3: Declarations) : Int = {
    var yygoto : Int = 0;
    yycur match {
      case _ => yynt = YYNTdecls(yyrule4(yyarg1,yyarg3)); yygoto = 4
    }
    while (yygoto == 0) {
      yynt match {
        case _:YYNTerror => return 0;
      }
    }
    yygoto-1
  }

  private def yystate5(yyarg1: Declarations, yyarg3: Declarations) : Int = {
    var yygoto : Int = 0;
    yycur match {
      case FarrowUbdTokens.CLS_BRACE() => yynext; yygoto = yystate6(yyarg1,yyarg3);
      case FarrowUbdTokens.OPN_BRACE() => yynext; yygoto = yystate4(yyarg3);
      case FarrowUbdTokens.ID(_) => yynt = YYNTdecls(yyrule3(yyarg3)); yygoto = 1
      case _ => yynt = YYNTerror("syntax error");
    }
    while (yygoto == 0) {
      yynt match {
        case _:YYNTerror => return 0;
      }
    }
    yygoto-1
  }

  private def yystate4(yyarg1: Declarations) : Int = {
    var yygoto : Int = 0;
    yycur match {
      case _ => yynt = YYNTdecls(yyrule2()); yygoto = 0
    }
    while (yygoto == 0) {
      yynt match {
        case YYNTdecls(yyarg3) => yygoto = yystate5(yyarg1,yyarg3);
        case _:YYNTerror => return 0;
      }
    }
    yygoto-1
  }

  private def yystate3(yyarg1: Declarations) : Int = {
    var yygoto : Int = 0;
    yycur match {
      case FarrowUbdTokens.YYEOF() => yynt = YYNTdecls(yyarg1); yygoto = 2;
      case FarrowUbdTokens.OPN_BRACE() => yynext; yygoto = yystate4(yyarg1);
      case FarrowUbdTokens.ID(_) => yynt = YYNTdecls(yyrule3(yyarg1)); yygoto = 1
      case _ => yynt = YYNTerror("syntax error");
    }
    while (yygoto == 0) {
      yynt match {
        case _:YYNTdecls => return 0;
        case _:YYNTerror => return 0;
      }
    }
    yygoto-1
  }

  private def yystate2() : Int = {
    var yygoto : Int = 0;
    yycur match {
      case FarrowUbdTokens.YYEOF() => yynt = YYNTdecls(yyrule2()); yygoto = 0
      case _ => yynt = YYNTdecls(yyrule2()); yygoto = 0
    }
    while (yygoto == 0) {
      yynt match {
        case YYNTdecls(yyarg1) => yygoto = yystate3(yyarg1);
        case _:YYNTerror => return 0;
      }
    }
    yygoto-1
  }

  private def yystate11(yyarg1: Symbol, yyarg3: Expression) : Int = {
    var yygoto : Int = 0;
    yycur match {
      case _ => yynt = YYNTdecl(yyrule5(yyarg1,yyarg3)); yygoto = 4
    }
    while (yygoto == 0) {
      yynt match {
        case _:YYNTerror => return 0;
      }
    }
    yygoto-1
  }

  private def yystate10(yyarg1: Symbol, yyarg3: Expression) : Int = {
    var yygoto : Int = 0;
    yycur match {
      case FarrowUbdTokens.MUL() => yynt = YYNTexpr(yyrule9(yyarg3)); yygoto = 1
      case FarrowUbdTokens.PLUS() => yynt = YYNTexpr(yyrule9(yyarg3)); yygoto = 1
      case FarrowUbdTokens.SEMICOLON() => yynext; yygoto = yystate11(yyarg1,yyarg3);
      case FarrowUbdTokens.DIV() => yynt = YYNTexpr(yyrule9(yyarg3)); yygoto = 1
      case FarrowUbdTokens.MINUS() => yynt = YYNTexpr(yyrule9(yyarg3)); yygoto = 1
      case _ => yynt = YYNTerror("syntax error");
    }
    while (yygoto == 0) {
      yynt match {
        case _:YYNTerror => return 0;
      }
    }
    yygoto-1
  }

  private def yystate9(yyarg1: Symbol) : Int = {
    var yygoto : Int = 0;
    yycur match {
      case FarrowUbdTokens.LITERAL(_) => yynt = YYNTexpr(yyrule8()); yygoto = 0
      case FarrowUbdTokens.ID(_) => yynt = YYNTexpr(yyrule8()); yygoto = 0
      case _ => yynt = YYNTerror("syntax error");
    }
    while (yygoto == 0) {
      yynt match {
        case YYNTexpr(yyarg3) => yygoto = yystate10(yyarg1,yyarg3);
        case _:YYNTerror => return 0;
      }
    }
    yygoto-1
  }

  private def yystate8(yyarg1: Symbol) : Int = {
    var yygoto : Int = 0;
    yycur match {
      case FarrowUbdTokens.EQ() => yynext; yygoto = yystate9(yyarg1);
      case _ => yynt = YYNTerror("syntax error");
    }
    while (yygoto == 0) {
      yynt match {
        case _:YYNTerror => return 0;
      }
    }
    yygoto-1
  }

  private def yystate12(yyarg1: Declaration) : Int = {
    var yygoto : Int = 0;
    yycur match {
      case FarrowUbdTokens.YYEOF() => yynt = YYNTdecl(yyarg1); yygoto = 2;
      case FarrowUbdTokens.CLS_BRACE() => yynt = YYNTdecl(yyarg1); yygoto = 2;
      case FarrowUbdTokens.OPN_BRACE() => yynt = YYNTdecl(yyarg1); yygoto = 2;
      case FarrowUbdTokens.ID(_) => yynt = YYNTdecl(yyarg1); yygoto = 2;
      case _ => yynt = YYNTerror("syntax error");
    }
    while (yygoto == 0) {
      yynt match {
        case _:YYNTdecl => return 0;
        case _:YYNTerror => return 0;
      }
    }
    yygoto-1
  }

  private def yystate7() : Int = {
    var yygoto : Int = 0;
    yycur match {
      case FarrowUbdTokens.ID(yyarg1) => yynext; yygoto = yystate8(yyarg1);
      case _ => yynt = YYNTerror("syntax error");
    }
    while (yygoto == 0) {
      yynt match {
        case YYNTdecl(yyarg1) => yygoto = yystate12(yyarg1);
        case _:YYNTerror => return 0;
      }
    }
    yygoto-1
  }

  private def yystate16() : Int = {
    var yygoto : Int = 0;
    yycur match {
      case _ => yynt = YYNTop(yyrule12()); yygoto = 1
    }
    while (yygoto == 0) {
      yynt match {
        case _:YYNTerror => return 0;
      }
    }
    yygoto-1
  }

  private def yystate17() : Int = {
    var yygoto : Int = 0;
    yycur match {
      case _ => yynt = YYNTop(yyrule10()); yygoto = 1
    }
    while (yygoto == 0) {
      yynt match {
        case _:YYNTerror => return 0;
      }
    }
    yygoto-1
  }

  private def yystate18() : Int = {
    var yygoto : Int = 0;
    yycur match {
      case _ => yynt = YYNTop(yyrule13()); yygoto = 1
    }
    while (yygoto == 0) {
      yynt match {
        case _:YYNTerror => return 0;
      }
    }
    yygoto-1
  }

  private def yystate19() : Int = {
    var yygoto : Int = 0;
    yycur match {
      case _ => yynt = YYNTop(yyrule11()); yygoto = 1
    }
    while (yygoto == 0) {
      yynt match {
        case _:YYNTerror => return 0;
      }
    }
    yygoto-1
  }

  private def yystate20(yyarg1: Operation) : Int = {
    var yygoto : Int = 0;
    yycur match {
      case FarrowUbdTokens.LITERAL(_) => yynt = YYNTop(yyarg1); yygoto = 2;
      case FarrowUbdTokens.ID(_) => yynt = YYNTop(yyarg1); yygoto = 2;
      case _ => yynt = YYNTerror("syntax error");
    }
    while (yygoto == 0) {
      yynt match {
        case _:YYNTop => return 0;
        case _:YYNTerror => return 0;
      }
    }
    yygoto-1
  }

  private def yystate15() : Int = {
    var yygoto : Int = 0;
    yycur match {
      case FarrowUbdTokens.MUL() => yynext; yygoto = yystate16();
      case FarrowUbdTokens.PLUS() => yynext; yygoto = yystate17();
      case FarrowUbdTokens.DIV() => yynext; yygoto = yystate18();
      case FarrowUbdTokens.MINUS() => yynext; yygoto = yystate19();
      case _ => yynt = YYNTerror("syntax error");
    }
    while (yygoto == 0) {
      yynt match {
        case YYNTop(yyarg1) => yygoto = yystate20(yyarg1);
        case _:YYNTerror => return 0;
      }
    }
    yygoto-1
  }

  private def yystate14(yyarg1: Term) : Int = {
    var yygoto : Int = 0;
    yycur match {
      case FarrowUbdTokens.MUL() => yynt = YYNTterm(yyarg1); yygoto = 2;
      case FarrowUbdTokens.PLUS() => yynt = YYNTterm(yyarg1); yygoto = 2;
      case FarrowUbdTokens.SEMICOLON() => yynt = YYNTterm(yyarg1); yygoto = 2;
      case FarrowUbdTokens.DIV() => yynt = YYNTterm(yyarg1); yygoto = 2;
      case FarrowUbdTokens.MINUS() => yynt = YYNTterm(yyarg1); yygoto = 2;
      case _ => yynt = YYNTerror("syntax error");
    }
    while (yygoto == 0) {
      yynt match {
        case _:YYNTterm => return 0;
        case _:YYNTerror => return 0;
      }
    }
    yygoto-1
  }

  private def yystate13() : Int = {
    var yygoto : Int = 0;
    yycur match {
      case FarrowUbdTokens.LITERAL(_) => yynt = YYNTterm(yyrule7()); yygoto = 0
      case FarrowUbdTokens.ID(_) => yynt = YYNTterm(yyrule6()); yygoto = 0
      case _ => yynt = YYNTerror("syntax error");
    }
    while (yygoto == 0) {
      yynt match {
        case YYNTterm(yyarg1) => yygoto = yystate14(yyarg1);
        case _:YYNTerror => return 0;
      }
    }
    yygoto-1
  }

  private def yystate1(yyarg1: Program) : Int = {
    var yygoto : Int = 0;
    yycur match {
      case FarrowUbdTokens.YYEOF() => yynt = YYNTprogram(yyarg1); yygoto = 2;
      case _ => yynt = YYNTerror("syntax error");
    }
    while (yygoto == 0) {
      yynt match {
        case _:YYNTprogram => return 0;
        case _:YYNTerror => return 0;
      }
    }
    yygoto-1
  }

  private def yystate0() : Int = {
    var yygoto : Int = 0;
    yycur match {
      case FarrowUbdTokens.YYEOF() => yynt = YYNTprogram(yyrule1()); yygoto = 0
      case _ => yynt = YYNTprogram(yyrule1()); yygoto = 0
    }
    while (yygoto == 0) {
      yynt match {
        case YYNTprogram(yyarg1) => yygoto = yystate1(yyarg1);
        case _:YYNTerror => return 0;
      }
    }
    yygoto-1
  }


  var scanner : FarrowUbdScanner = null;
  var filename : String = "<unknown>";
  var result : Program = null;

  def get_result() : Program = result;

  def reset(sc : FarrowUbdScanner, fn : String) : Unit = {
    filename = fn;
    scanner = sc;
    yyreset(sc)
  };

  override def get_line_number() : Int = scanner.getLineNumber();

  /* This function is called automatically when Bison detects a parse error. */
  def yyerror(message : String) : Unit = {
    print (filename + ":" + scanner.getLineNumber() + ": " +
      message + ", at or near " + yycur + "\n");
  };

  override def program(ds:Declarations) : Program = {
    var res = super.program(ds);
    result = res;
    res
  }

}
