// Generated by aps2scala version 0.3.6
import basic_implicit._;
object farrow_ubd_synth_implicit {
  val farrow_ubd_loaded = true;
  import symbol_implicit._;
  import table_implicit._;
  import flat_implicit._;
  import farrow_ubd_tree_implicit._;
  type T_FARROW_UBD[T_T] = T_T;
}
import farrow_ubd_synth_implicit._;

import symbol_implicit._;
import table_implicit._;
import flat_implicit._;
import farrow_ubd_tree_implicit._;
trait C_FARROW_UBD_SYNTH[T_Result, T_T] extends C_TYPE[T_Result]
  with C_FARROW_UBD_TREE[T_Result] {
  type T_IntegerLattice;
  val t_IntegerLattice : C_TYPE[T_IntegerLattice]
    with C_FLAT_LATTICE[T_IntegerLattice,T_Integer];
  type T_DeclPairLattice;
  val t_DeclPairLattice : C_TYPE[T_DeclPairLattice]
    with C_TABLE_LATTICE[T_DeclPairLattice,T_Symbol,T_IntegerLattice];
  type T_Messages;
  val t_Messages : C_TYPE[T_Messages]
    with C_SET[T_Messages,T_String];
  val v_decl_name : (T_Declaration) => T_Symbol;
  val v_decl_pair : (T_Declaration) => T_DeclPairLattice;
  val v_decl_env : (T_Declaration) => T_DeclPairLattice;
  val v_decl_errs : (T_Declaration) => T_Messages;
  val v_decls_defs : (T_Declarations) => T_DeclPairLattice;
  val v_decls_env : (T_Declarations) => T_DeclPairLattice;
  val v_decls_errs : (T_Declarations) => T_Messages;
  val v_expr_val : (T_Expression) => T_IntegerLattice;
  val v_expr_env : (T_Expression) => T_DeclPairLattice;
  val v_expr_errs : (T_Expression) => T_Messages;
  val v_term_val : (T_Term) => T_IntegerLattice;
  val v_term_env : (T_Term) => T_DeclPairLattice;
  val v_term_errs : (T_Term) => T_Messages;
  val v_op_val : (T_Operation) => T_IntegerLattice;
  val v_op_lval : (T_Operation) => T_IntegerLattice;
  val v_op_rval : (T_Operation) => T_IntegerLattice;
  val v_program_errs : (T_Program) => T_Messages;
}

class M_FARROW_UBD_SYNTH[T_T](name : String,val t_T : C_TYPE[T_T]
  with C_FARROW_UBD_TREE[T_T])
  extends Module(name)
    with C_FARROW_UBD_SYNTH[T_T,T_T]
{
  type T_Result = T_T;
  val v_equal = t_T.v_equal;
  val v_string = t_T.v_string;
  val v_assert = t_T.v_assert;
  val v_node_equivalent = t_T.v_node_equivalent;
  type T_Declaration = t_T.T_Declaration;
  val t_Declaration = t_T.t_Declaration;
  type T_Declarations = t_T.T_Declarations;
  val t_Declarations = t_T.t_Declarations;
  type T_Expression = t_T.T_Expression;
  val t_Expression = t_T.t_Expression;
  type T_Term = t_T.T_Term;
  val t_Term = t_T.t_Term;
  type T_Operation = t_T.T_Operation;
  val t_Operation = t_T.t_Operation;
  type T_Program = t_T.T_Program;
  val t_Program = t_T.t_Program;
  val p_scope = t_T.p_scope;
  val v_scope = t_T.v_scope;
  val p_decl_assign = t_T.p_decl_assign;
  val v_decl_assign = t_T.v_decl_assign;
  val p_decls_empty = t_T.p_decls_empty;
  val v_decls_empty = t_T.v_decls_empty;
  val p_decls_append = t_T.p_decls_append;
  val v_decls_append = t_T.v_decls_append;
  val p_decls_append_scope = t_T.p_decls_append_scope;
  val v_decls_append_scope = t_T.v_decls_append_scope;
  val p_expr_term = t_T.p_expr_term;
  val v_expr_term = t_T.v_expr_term;
  val p_op_add = t_T.p_op_add;
  val v_op_add = t_T.v_op_add;
  val p_op_mul = t_T.p_op_mul;
  val v_op_mul = t_T.v_op_mul;
  val p_op_sub = t_T.p_op_sub;
  val v_op_sub = t_T.v_op_sub;
  val p_op_div = t_T.p_op_div;
  val v_op_div = t_T.v_op_div;
  val p_expr_apply = t_T.p_expr_apply;
  val v_expr_apply = t_T.v_expr_apply;
  val p_term_variable = t_T.p_term_variable;
  val v_term_variable = t_T.v_term_variable;
  val p_term_literal = t_T.p_term_literal;
  val v_term_literal = t_T.v_term_literal;
  val p_program = t_T.p_program;
  val v_program = t_T.v_program;

  val t_Result : this.type = this;
  val t_IntegerLattice = new M_FLAT_LATTICE[T_Integer](
    "IntegerLattice",
    t_Integer
  )

  type T_IntegerLattice = /*TI*/T_FLAT_LATTICE[T_Integer];
  val t_DeclPairLattice = new M_TABLE_LATTICE[T_Symbol,T_IntegerLattice](
    "DeclPairLattice",
    t_Symbol,
    t_IntegerLattice
  )

  type T_DeclPairLattice = /*TI*/T_TABLE_LATTICE[T_Symbol,T_IntegerLattice];
  val t_Messages = new M_SET[T_String](
    "Messages",
    t_String
  )

  type T_Messages = /*TI*/T_SET[T_String];
  private class E_decl_name(anchor : T_Declaration) extends Evaluation[T_Declaration,T_Symbol](anchor,anchor.toString()+"."+"decl_name") {
  }
  private object a_decl_name extends Attribute[T_Declaration,T_Symbol](t_Declaration,t_Symbol,"decl_name") {
    override def createEvaluation(anchor : T_Declaration) : Evaluation[T_Declaration,T_Symbol] = new E_decl_name(anchor);
  }
  val v_decl_name : T_Declaration => T_Symbol = a_decl_name.get _;

  private class E_decl_pair(anchor : T_Declaration) extends Evaluation[T_Declaration,T_DeclPairLattice](anchor,anchor.toString()+"."+"decl_pair") with CircularEvaluation[T_Declaration,T_DeclPairLattice] with CollectionEvaluation[T_Declaration,T_DeclPairLattice] with StaticCircularEvaluation[T_Declaration,T_DeclPairLattice] {
    override def initial : T_DeclPairLattice = t_DeclPairLattice.v_initial;
    override def combine(v1 : T_DeclPairLattice, v2 : T_DeclPairLattice) = t_DeclPairLattice.v_combine(v1,v2);
    def lattice : C_LATTICE[T_DeclPairLattice] = t_DeclPairLattice;

  }
  private object a_decl_pair extends Attribute[T_Declaration,T_DeclPairLattice](t_Declaration,t_DeclPairLattice,"decl_pair")
    with ChangeTrackingAttribute[T_Declaration,T_DeclPairLattice] {
    override def createEvaluation(anchor : T_Declaration) : Evaluation[T_Declaration,T_DeclPairLattice] = new E_decl_pair(anchor);
  }
  val v_decl_pair : T_Declaration => T_DeclPairLattice = a_decl_pair.get _;

  private class E_decl_env(anchor : T_Declaration) extends Evaluation[T_Declaration,T_DeclPairLattice](anchor,anchor.toString()+"."+"decl_env") with CircularEvaluation[T_Declaration,T_DeclPairLattice] with CollectionEvaluation[T_Declaration,T_DeclPairLattice] with StaticCircularEvaluation[T_Declaration,T_DeclPairLattice] {
    override def initial : T_DeclPairLattice = t_DeclPairLattice.v_initial;
    override def combine(v1 : T_DeclPairLattice, v2 : T_DeclPairLattice) = t_DeclPairLattice.v_combine(v1,v2);
    def lattice : C_LATTICE[T_DeclPairLattice] = t_DeclPairLattice;

  }
  private object a_decl_env extends Attribute[T_Declaration,T_DeclPairLattice](t_Declaration,t_DeclPairLattice,"decl_env")
    with ChangeTrackingAttribute[T_Declaration,T_DeclPairLattice] {
    override def createEvaluation(anchor : T_Declaration) : Evaluation[T_Declaration,T_DeclPairLattice] = new E_decl_env(anchor);
  }
  val v_decl_env : T_Declaration => T_DeclPairLattice = a_decl_env.get _;

  private class E_decl_errs(anchor : T_Declaration) extends Evaluation[T_Declaration,T_Messages](anchor,anchor.toString()+"."+"decl_errs") {
  }
  private object a_decl_errs extends Attribute[T_Declaration,T_Messages](t_Declaration,t_Messages,"decl_errs") {
    override def createEvaluation(anchor : T_Declaration) : Evaluation[T_Declaration,T_Messages] = new E_decl_errs(anchor);
  }
  val v_decl_errs : T_Declaration => T_Messages = a_decl_errs.get _;

  private class E_decls_defs(anchor : T_Declarations) extends Evaluation[T_Declarations,T_DeclPairLattice](anchor,anchor.toString()+"."+"decls_defs") with CircularEvaluation[T_Declarations,T_DeclPairLattice] with CollectionEvaluation[T_Declarations,T_DeclPairLattice] with StaticCircularEvaluation[T_Declarations,T_DeclPairLattice] {
    override def initial : T_DeclPairLattice = t_DeclPairLattice.v_initial;
    override def combine(v1 : T_DeclPairLattice, v2 : T_DeclPairLattice) = t_DeclPairLattice.v_combine(v1,v2);
    def lattice : C_LATTICE[T_DeclPairLattice] = t_DeclPairLattice;

  }
  private object a_decls_defs extends Attribute[T_Declarations,T_DeclPairLattice](t_Declarations,t_DeclPairLattice,"decls_defs")
    with ChangeTrackingAttribute[T_Declarations,T_DeclPairLattice] {
    override def createEvaluation(anchor : T_Declarations) : Evaluation[T_Declarations,T_DeclPairLattice] = new E_decls_defs(anchor);
  }
  val v_decls_defs : T_Declarations => T_DeclPairLattice = a_decls_defs.get _;

  private class E_decls_env(anchor : T_Declarations) extends Evaluation[T_Declarations,T_DeclPairLattice](anchor,anchor.toString()+"."+"decls_env") with CircularEvaluation[T_Declarations,T_DeclPairLattice] with CollectionEvaluation[T_Declarations,T_DeclPairLattice] with StaticCircularEvaluation[T_Declarations,T_DeclPairLattice] {
    override def initial : T_DeclPairLattice = t_DeclPairLattice.v_initial;
    override def combine(v1 : T_DeclPairLattice, v2 : T_DeclPairLattice) = t_DeclPairLattice.v_combine(v1,v2);
    def lattice : C_LATTICE[T_DeclPairLattice] = t_DeclPairLattice;

  }
  private object a_decls_env extends Attribute[T_Declarations,T_DeclPairLattice](t_Declarations,t_DeclPairLattice,"decls_env")
    with ChangeTrackingAttribute[T_Declarations,T_DeclPairLattice] {
    override def createEvaluation(anchor : T_Declarations) : Evaluation[T_Declarations,T_DeclPairLattice] = new E_decls_env(anchor);
  }
  val v_decls_env : T_Declarations => T_DeclPairLattice = a_decls_env.get _;

  private class E_decls_errs(anchor : T_Declarations) extends Evaluation[T_Declarations,T_Messages](anchor,anchor.toString()+"."+"decls_errs") {
  }
  private object a_decls_errs extends Attribute[T_Declarations,T_Messages](t_Declarations,t_Messages,"decls_errs") {
    override def createEvaluation(anchor : T_Declarations) : Evaluation[T_Declarations,T_Messages] = new E_decls_errs(anchor);
  }
  val v_decls_errs : T_Declarations => T_Messages = a_decls_errs.get _;

  private class E_expr_val(anchor : T_Expression) extends Evaluation[T_Expression,T_IntegerLattice](anchor,anchor.toString()+"."+"expr_val") with CircularEvaluation[T_Expression,T_IntegerLattice] with StaticCircularEvaluation[T_Expression,T_IntegerLattice] {
    def lattice : C_LATTICE[T_IntegerLattice] = t_IntegerLattice;

  }
  private object a_expr_val extends Attribute[T_Expression,T_IntegerLattice](t_Expression,t_IntegerLattice,"expr_val")
    with ChangeTrackingAttribute[T_Expression,T_IntegerLattice] {
    override def createEvaluation(anchor : T_Expression) : Evaluation[T_Expression,T_IntegerLattice] = new E_expr_val(anchor);
  }
  val v_expr_val : T_Expression => T_IntegerLattice = a_expr_val.get _;

  private class E_expr_env(anchor : T_Expression) extends Evaluation[T_Expression,T_DeclPairLattice](anchor,anchor.toString()+"."+"expr_env") with CircularEvaluation[T_Expression,T_DeclPairLattice] with CollectionEvaluation[T_Expression,T_DeclPairLattice] with StaticCircularEvaluation[T_Expression,T_DeclPairLattice] {
    override def initial : T_DeclPairLattice = t_DeclPairLattice.v_initial;
    override def combine(v1 : T_DeclPairLattice, v2 : T_DeclPairLattice) = t_DeclPairLattice.v_combine(v1,v2);
    def lattice : C_LATTICE[T_DeclPairLattice] = t_DeclPairLattice;

  }
  private object a_expr_env extends Attribute[T_Expression,T_DeclPairLattice](t_Expression,t_DeclPairLattice,"expr_env")
    with ChangeTrackingAttribute[T_Expression,T_DeclPairLattice] {
    override def createEvaluation(anchor : T_Expression) : Evaluation[T_Expression,T_DeclPairLattice] = new E_expr_env(anchor);
  }
  val v_expr_env : T_Expression => T_DeclPairLattice = a_expr_env.get _;

  private class E_expr_errs(anchor : T_Expression) extends Evaluation[T_Expression,T_Messages](anchor,anchor.toString()+"."+"expr_errs") {
  }
  private object a_expr_errs extends Attribute[T_Expression,T_Messages](t_Expression,t_Messages,"expr_errs") {
    override def createEvaluation(anchor : T_Expression) : Evaluation[T_Expression,T_Messages] = new E_expr_errs(anchor);
  }
  val v_expr_errs : T_Expression => T_Messages = a_expr_errs.get _;

  private class E_term_val(anchor : T_Term) extends Evaluation[T_Term,T_IntegerLattice](anchor,anchor.toString()+"."+"term_val") with CircularEvaluation[T_Term,T_IntegerLattice] with StaticCircularEvaluation[T_Term,T_IntegerLattice] {
    def lattice : C_LATTICE[T_IntegerLattice] = t_IntegerLattice;

  }
  private object a_term_val extends Attribute[T_Term,T_IntegerLattice](t_Term,t_IntegerLattice,"term_val")
    with ChangeTrackingAttribute[T_Term,T_IntegerLattice] {
    override def createEvaluation(anchor : T_Term) : Evaluation[T_Term,T_IntegerLattice] = new E_term_val(anchor);
  }
  val v_term_val : T_Term => T_IntegerLattice = a_term_val.get _;

  private class E_term_env(anchor : T_Term) extends Evaluation[T_Term,T_DeclPairLattice](anchor,anchor.toString()+"."+"term_env") with CircularEvaluation[T_Term,T_DeclPairLattice] with CollectionEvaluation[T_Term,T_DeclPairLattice] with StaticCircularEvaluation[T_Term,T_DeclPairLattice] {
    override def initial : T_DeclPairLattice = t_DeclPairLattice.v_initial;
    override def combine(v1 : T_DeclPairLattice, v2 : T_DeclPairLattice) = t_DeclPairLattice.v_combine(v1,v2);
    def lattice : C_LATTICE[T_DeclPairLattice] = t_DeclPairLattice;

  }
  private object a_term_env extends Attribute[T_Term,T_DeclPairLattice](t_Term,t_DeclPairLattice,"term_env")
    with ChangeTrackingAttribute[T_Term,T_DeclPairLattice] {
    override def createEvaluation(anchor : T_Term) : Evaluation[T_Term,T_DeclPairLattice] = new E_term_env(anchor);
  }
  val v_term_env : T_Term => T_DeclPairLattice = a_term_env.get _;

  private class E_term_errs(anchor : T_Term) extends Evaluation[T_Term,T_Messages](anchor,anchor.toString()+"."+"term_errs") {
  }
  private object a_term_errs extends Attribute[T_Term,T_Messages](t_Term,t_Messages,"term_errs") {
    override def createEvaluation(anchor : T_Term) : Evaluation[T_Term,T_Messages] = new E_term_errs(anchor);
  }
  val v_term_errs : T_Term => T_Messages = a_term_errs.get _;

  private class E_op_val(anchor : T_Operation) extends Evaluation[T_Operation,T_IntegerLattice](anchor,anchor.toString()+"."+"op_val") with CircularEvaluation[T_Operation,T_IntegerLattice] with StaticCircularEvaluation[T_Operation,T_IntegerLattice] {
    def lattice : C_LATTICE[T_IntegerLattice] = t_IntegerLattice;

  }
  private object a_op_val extends Attribute[T_Operation,T_IntegerLattice](t_Operation,t_IntegerLattice,"op_val")
    with ChangeTrackingAttribute[T_Operation,T_IntegerLattice] {
    override def createEvaluation(anchor : T_Operation) : Evaluation[T_Operation,T_IntegerLattice] = new E_op_val(anchor);
  }
  val v_op_val : T_Operation => T_IntegerLattice = a_op_val.get _;

  private class E_op_lval(anchor : T_Operation) extends Evaluation[T_Operation,T_IntegerLattice](anchor,anchor.toString()+"."+"op_lval") with CircularEvaluation[T_Operation,T_IntegerLattice] with StaticCircularEvaluation[T_Operation,T_IntegerLattice] {
    def lattice : C_LATTICE[T_IntegerLattice] = t_IntegerLattice;

  }
  private object a_op_lval extends Attribute[T_Operation,T_IntegerLattice](t_Operation,t_IntegerLattice,"op_lval")
    with ChangeTrackingAttribute[T_Operation,T_IntegerLattice] {
    override def createEvaluation(anchor : T_Operation) : Evaluation[T_Operation,T_IntegerLattice] = new E_op_lval(anchor);
  }
  val v_op_lval : T_Operation => T_IntegerLattice = a_op_lval.get _;

  private class E_op_rval(anchor : T_Operation) extends Evaluation[T_Operation,T_IntegerLattice](anchor,anchor.toString()+"."+"op_rval") with CircularEvaluation[T_Operation,T_IntegerLattice] with StaticCircularEvaluation[T_Operation,T_IntegerLattice] {
    def lattice : C_LATTICE[T_IntegerLattice] = t_IntegerLattice;

  }
  private object a_op_rval extends Attribute[T_Operation,T_IntegerLattice](t_Operation,t_IntegerLattice,"op_rval")
    with ChangeTrackingAttribute[T_Operation,T_IntegerLattice] {
    override def createEvaluation(anchor : T_Operation) : Evaluation[T_Operation,T_IntegerLattice] = new E_op_rval(anchor);
  }
  val v_op_rval : T_Operation => T_IntegerLattice = a_op_rval.get _;

  private class E_program_errs(anchor : T_Program) extends Evaluation[T_Program,T_Messages](anchor,anchor.toString()+"."+"program_errs") {
  }
  private object a_program_errs extends Attribute[T_Program,T_Messages](t_Program,t_Messages,"program_errs") {
    override def createEvaluation(anchor : T_Program) : Evaluation[T_Program,T_Messages] = new E_program_errs(anchor);
  }
  val v_program_errs : T_Program => T_Messages = a_program_errs.get _;

  private class E1_variable_value(anchor : t_Result.T_Term) extends Evaluation[t_Result.T_Term,T_IntegerLattice](anchor,anchor.toString()+"."+"variable_value") with CircularEvaluation[t_Result.T_Term,T_IntegerLattice] with StaticCircularEvaluation[t_Result.T_Term,T_IntegerLattice] {
    def lattice : C_LATTICE[T_IntegerLattice] = t_IntegerLattice;

  }
  private object a1_variable_value extends Attribute[t_Result.T_Term,T_IntegerLattice](t_Result.t_Term,t_IntegerLattice,"variable_value")
    with ChangeTrackingAttribute[t_Result.T_Term,T_IntegerLattice] {
    override def createEvaluation(anchor : t_Result.T_Term) : Evaluation[t_Result.T_Term,T_IntegerLattice] = new E1_variable_value(anchor);
  }
  private class E2_variable_defined(anchor : t_Result.T_Term) extends Evaluation[t_Result.T_Term,T_OrLattice](anchor,anchor.toString()+"."+"variable_defined") with CircularEvaluation[t_Result.T_Term,T_OrLattice] with StaticCircularEvaluation[t_Result.T_Term,T_OrLattice] {
    def lattice : C_LATTICE[T_OrLattice] = t_OrLattice;

  }
  private object a2_variable_defined extends Attribute[t_Result.T_Term,T_OrLattice](t_Result.t_Term,t_OrLattice,"variable_defined")
    with ChangeTrackingAttribute[t_Result.T_Term,T_OrLattice] {
    override def createEvaluation(anchor : t_Result.T_Term) : Evaluation[t_Result.T_Term,T_OrLattice] = new E2_variable_defined(anchor);
  }

  def eval_Declaration_decl_errs(node: T_Declaration,
                                 v_decl_env: T_DeclPairLattice,
                                 v_decl_pair: T_DeclPairLattice,
                                 v_decl_name: T_Symbol)(implicit isInsideFixedPoint: Boolean, changed: AtomicBoolean): T_Messages = {
    if (!isInsideFixedPoint) {
      a_decl_errs.checkNode(node).status match {
        case Evaluation.ASSIGNED => return a_decl_errs.get(node)
        case _ => ()
      };
    }
    val anchor = node;
    val result = node match {
      case p_decl_assign(v_self,v_s,v_e) => {
        eval_Expression_expr_errs(
          v_e,
          v_decl_env,
          eval_Expression_expr_val(
            v_e,
            v_decl_env
          )
        )
      }
      case _ => throw new RuntimeException("failed pattern matching: " + node)
    };
    a_decl_errs.assign(node, result);
    a_decl_errs.get(node);
    result
  }

  def eval_Declaration_decl_pair(node: T_Declaration,
                                 v_decl_env: T_DeclPairLattice,
                                 v_decl_name: T_Symbol)(implicit isInsideFixedPoint: Boolean, changed: AtomicBoolean): T_DeclPairLattice = {
    if (!isInsideFixedPoint) {
      a_decl_pair.checkNode(node).status match {
        case Evaluation.ASSIGNED => return a_decl_pair.get(node)
        case _ => ()
      };
    }
    val anchor = node;
    val result = node match {
      case p_decl_assign(v_self,v_s,v_e) => {
        {
          val prevIsInsideFixedPoint3 = isInsideFixedPoint;
          val prevChanged3 = changed;
          val newChanged3 = new AtomicBoolean(false);
          do {
            newChanged3.set(false);
            implicit val isInsideFixedPoint: Boolean = true;
            implicit val changed: AtomicBoolean = newChanged3;
            a_decl_pair.assign(node, t_DeclPairLattice.v_table_entry(v_s,
              eval_Expression_expr_val(
                v_e,
                v_decl_env
              )), changed);
          } while (newChanged3.get && !prevIsInsideFixedPoint3)
          prevChanged3.compareAndSet(false, newChanged3.get);
          a_decl_pair.get(node)
        }
      }
      case _ => throw new RuntimeException("failed pattern matching: " + node)
    };
    a_decl_pair.assign(node, result);
    a_decl_pair.get(node);
    result
  }

  def eval_Declaration_decl_name(node: T_Declaration)(implicit isInsideFixedPoint: Boolean, changed: AtomicBoolean): T_Symbol = {
    if (!isInsideFixedPoint) {
      a_decl_name.checkNode(node).status match {
        case Evaluation.ASSIGNED => return a_decl_name.get(node)
        case _ => ()
      };
    }
    val anchor = node;
    val result = node match {
      case p_decl_assign(v_self,v_s,v_e) => {
        v_s
      }
      case _ => throw new RuntimeException("failed pattern matching: " + node)
    };
    a_decl_name.assign(node, result);
    a_decl_name.get(node);
    result
  }

  def eval_Declarations_decls_errs(node: T_Declarations,
                                   v_decls_env: T_DeclPairLattice,
                                   v_decls_defs: T_DeclPairLattice)(implicit isInsideFixedPoint: Boolean, changed: AtomicBoolean): T_Messages = {
    if (!isInsideFixedPoint) {
      a_decls_errs.checkNode(node).status match {
        case Evaluation.ASSIGNED => return a_decls_errs.get(node)
        case _ => ()
      };
    }
    val anchor = node;
    val result = node match {
      case p_scope(v_self,v_ds) => {
        eval_Declarations_decls_errs(
          v_ds,
          eval_Declarations_decls_defs(
            v_ds,
            /* circular dependency detected for ds.decls_defs, dumping as attribute access */ a_decls_defs.get(v_ds)
          ),
          /* circular dependency detected for ds.decls_defs, dumping as attribute access */ a_decls_defs.get(v_ds)
        )
      }
      case p_decls_empty(v_self) => {
        t_Messages.v_none()
      }
      case p_decls_append(v_self,v_ds,v_d) => {
        {
          val node2 = t_DeclPairLattice.v_select(eval_Declarations_decls_defs(
            v_ds,
            v_decls_env
          ),
            eval_Declaration_decl_name(
              v_d
            ));
          node2 match {
            case t_DeclPairLattice.p_table_entry(_,v_0,v_value) => {
              new M__basic_19[ T_String,T_Messages](t_String,t_Messages).v__op_5w(new M__basic_19[ T_String,T_Messages](t_String,t_Messages).v__op_5w(t_Messages.v_single(new M__basic_18[ T_String](t_String).v__op_ss("identifier ",
                new M__basic_18[ T_String](t_String).v__op_ss(v_symbol_name(eval_Declaration_decl_name(
                  v_d
                )),
                  " is multiply defined"))),
                eval_Declarations_decls_errs(
                  v_ds,
                  v_decls_env,
                  /* circular dependency detected for ds.decls_defs, dumping as attribute access */ a_decls_defs.get(v_ds)
                )),
                eval_Declaration_decl_errs(
                  v_d,
                  v_decls_env,
                  eval_Declaration_decl_pair(
                    v_d,
                    v_decls_env,
                    eval_Declaration_decl_name(
                      v_d
                    )
                  ),
                  eval_Declaration_decl_name(
                    v_d
                  )
                ))
            }
            case _ => {
              new M__basic_19[ T_String,T_Messages](t_String,t_Messages).v__op_5w(eval_Declarations_decls_errs(
                v_ds,
                v_decls_env,
                /* circular dependency detected for ds.decls_defs, dumping as attribute access */ a_decls_defs.get(v_ds)
              ),
                eval_Declaration_decl_errs(
                  v_d,
                  v_decls_env,
                  /* circular dependency detected for d.decl_pair, dumping as attribute access */ a_decl_pair.get(v_d),
                  eval_Declaration_decl_name(
                    v_d
                  )
                ))
            }
          }
        }

      }
      case p_decls_append_scope(v_self,v_ds,v_inner) => {
        new M__basic_19[ T_String,T_Messages](t_String,t_Messages).v__op_5w(eval_Declarations_decls_errs(
          v_ds,
          v_decls_env,
          eval_Declarations_decls_defs(
            v_ds,
            v_decls_env
          )
        ),
          eval_Declarations_decls_errs(
            v_inner,
            eval_Declarations_decls_defs(
              v_inner,
              /* circular dependency detected for inner.decls_defs, dumping as attribute access */ a_decls_defs.get(v_inner)
            ),
            /* circular dependency detected for inner.decls_defs, dumping as attribute access */ a_decls_defs.get(v_inner)
          ))
      }
      case _ => throw new RuntimeException("failed pattern matching: " + node)
    };
    a_decls_errs.assign(node, result);
    a_decls_errs.get(node);
    result
  }

  def eval_Declarations_decls_defs(node: T_Declarations,
                                   v_decls_env: T_DeclPairLattice)(implicit isInsideFixedPoint: Boolean, changed: AtomicBoolean): T_DeclPairLattice = {
    if (!isInsideFixedPoint) {
      a_decls_defs.checkNode(node).status match {
        case Evaluation.ASSIGNED => return a_decls_defs.get(node)
        case _ => ()
      };
    }
    val anchor = node;
    val result = node match {
      case p_scope(v_self,v_ds) => {
        {
          val prevIsInsideFixedPoint3 = isInsideFixedPoint;
          val prevChanged3 = changed;
          val newChanged3 = new AtomicBoolean(false);
          do {
            newChanged3.set(false);
            implicit val isInsideFixedPoint: Boolean = true;
            implicit val changed: AtomicBoolean = newChanged3;
            a_decls_defs.assign(node, eval_Declarations_decls_defs(
              v_ds,
              /* circular dependency detected for ds.decls_defs, dumping as attribute access */ a_decls_defs.get(v_ds)
            ), changed);
          } while (newChanged3.get && !prevIsInsideFixedPoint3)
          prevChanged3.compareAndSet(false, newChanged3.get);
          a_decls_defs.get(node)
        }
      }
      case p_decls_empty(v_self) => {
        {
          val prevIsInsideFixedPoint3 = isInsideFixedPoint;
          val prevChanged3 = changed;
          val newChanged3 = new AtomicBoolean(false);
          do {
            newChanged3.set(false);
            implicit val isInsideFixedPoint: Boolean = true;
            implicit val changed: AtomicBoolean = newChanged3;
            a_decls_defs.assign(node, t_DeclPairLattice.v_bottom, changed);
          } while (newChanged3.get && !prevIsInsideFixedPoint3)
          prevChanged3.compareAndSet(false, newChanged3.get);
          a_decls_defs.get(node)
        }
      }
      case p_decls_append(v_self,v_ds,v_d) => {
        {
          val prevIsInsideFixedPoint3 = isInsideFixedPoint;
          val prevChanged3 = changed;
          val newChanged3 = new AtomicBoolean(false);
          do {
            newChanged3.set(false);
            implicit val isInsideFixedPoint: Boolean = true;
            implicit val changed: AtomicBoolean = newChanged3;
            a_decls_defs.assign(node, {
              val node4 = t_DeclPairLattice.v_select(eval_Declarations_decls_defs(
                v_ds,
                v_decls_env
              ),
                eval_Declaration_decl_name(
                  v_d
                ));
              node4 match {
                case t_DeclPairLattice.p_table_entry(_,v_0,v_value) => {
                  /* circular dependency detected for ds.decls_defs, dumping as attribute access */ a_decls_defs.get(v_ds)
                }
                case _ => {
                  t_DeclPairLattice.v_join(/* circular dependency detected for ds.decls_defs, dumping as attribute access */ a_decls_defs.get(v_ds),
                    eval_Declaration_decl_pair(
                      v_d,
                      v_decls_env,
                      eval_Declaration_decl_name(
                        v_d
                      )
                    ))
                }
              }
            }
              , changed);
          } while (newChanged3.get && !prevIsInsideFixedPoint3)
          prevChanged3.compareAndSet(false, newChanged3.get);
          a_decls_defs.get(node)
        }
      }
      case p_decls_append_scope(v_self,v_ds,v_inner) => {
        {
          val prevIsInsideFixedPoint3 = isInsideFixedPoint;
          val prevChanged3 = changed;
          val newChanged3 = new AtomicBoolean(false);
          do {
            newChanged3.set(false);
            implicit val isInsideFixedPoint: Boolean = true;
            implicit val changed: AtomicBoolean = newChanged3;
            a_decls_defs.assign(node, t_DeclPairLattice.v_join(eval_Declarations_decls_defs(
              v_ds,
              v_decls_env
            ),
              eval_Declarations_decls_defs(
                v_inner,
                /* circular dependency detected for inner.decls_defs, dumping as attribute access */ a_decls_defs.get(v_inner)
              )), changed);
          } while (newChanged3.get && !prevIsInsideFixedPoint3)
          prevChanged3.compareAndSet(false, newChanged3.get);
          a_decls_defs.get(node)
        }
      }
      case _ => throw new RuntimeException("failed pattern matching: " + node)
    };
    a_decls_defs.assign(node, result);
    a_decls_defs.get(node);
    result
  }

  def eval_Expression_expr_errs(node: T_Expression,
                                v_expr_env: T_DeclPairLattice,
                                v_expr_val: T_IntegerLattice)(implicit isInsideFixedPoint: Boolean, changed: AtomicBoolean): T_Messages = {
    if (!isInsideFixedPoint) {
      a_expr_errs.checkNode(node).status match {
        case Evaluation.ASSIGNED => return a_expr_errs.get(node)
        case _ => ()
      };
    }
    val anchor = node;
    val result = node match {
      case p_expr_term(v_self,v_t) => {
        eval_Term_term_errs(
          v_t,
          v_expr_env,
          eval_Term_term_val(
            v_t,
            v_expr_env
          )
        )
      }
      case p_expr_apply(v_self,v_e,v_op,v_t) => {
        new M__basic_19[ T_String,T_Messages](t_String,t_Messages).v__op_5w(eval_Expression_expr_errs(
          v_e,
          v_expr_env,
          eval_Expression_expr_val(
            v_e,
            v_expr_env
          )
        ),
          eval_Term_term_errs(
            v_t,
            v_expr_env,
            eval_Term_term_val(
              v_t,
              v_expr_env
            )
          ))
      }
      case _ => throw new RuntimeException("failed pattern matching: " + node)
    };
    a_expr_errs.assign(node, result);
    a_expr_errs.get(node);
    result
  }

  def eval_Expression_expr_val(node: T_Expression,
                               v_expr_env: T_DeclPairLattice)(implicit isInsideFixedPoint: Boolean, changed: AtomicBoolean): T_IntegerLattice = {
    if (!isInsideFixedPoint) {
      a_expr_val.checkNode(node).status match {
        case Evaluation.ASSIGNED => return a_expr_val.get(node)
        case _ => ()
      };
    }
    val anchor = node;
    val result = node match {
      case p_expr_term(v_self,v_t) => {
        {
          val prevIsInsideFixedPoint3 = isInsideFixedPoint;
          val prevChanged3 = changed;
          val newChanged3 = new AtomicBoolean(false);
          do {
            newChanged3.set(false);
            implicit val isInsideFixedPoint: Boolean = true;
            implicit val changed: AtomicBoolean = newChanged3;
            a_expr_val.assign(node, eval_Term_term_val(
              v_t,
              v_expr_env
            ), changed);
          } while (newChanged3.get && !prevIsInsideFixedPoint3)
          prevChanged3.compareAndSet(false, newChanged3.get);
          a_expr_val.get(node)
        }
      }
      case p_expr_apply(v_self,v_e,v_op,v_t) => {
        {
          val prevIsInsideFixedPoint3 = isInsideFixedPoint;
          val prevChanged3 = changed;
          val newChanged3 = new AtomicBoolean(false);
          do {
            newChanged3.set(false);
            implicit val isInsideFixedPoint: Boolean = true;
            implicit val changed: AtomicBoolean = newChanged3;
            a_expr_val.assign(node, eval_Operation_op_val(
              v_op,
              eval_Term_term_val(
                v_t,
                v_expr_env
              ),
              eval_Expression_expr_val(
                v_e,
                v_expr_env
              )
            ), changed);
          } while (newChanged3.get && !prevIsInsideFixedPoint3)
          prevChanged3.compareAndSet(false, newChanged3.get);
          a_expr_val.get(node)
        }
      }
      case _ => throw new RuntimeException("failed pattern matching: " + node)
    };
    a_expr_val.assign(node, result);
    a_expr_val.get(node);
    result
  }

  def eval_Term_term_errs(node: T_Term,
                          v_term_env: T_DeclPairLattice,
                          v_term_val: T_IntegerLattice)(implicit isInsideFixedPoint: Boolean, changed: AtomicBoolean): T_Messages = {
    if (!isInsideFixedPoint) {
      a_term_errs.checkNode(node).status match {
        case Evaluation.ASSIGNED => return a_term_errs.get(node)
        case _ => ()
      };
    }
    val anchor = node;
    val result = node match {
      case p_term_variable(v_self,v_s) => {
        {
          val node4 = t_DeclPairLattice.v_select(v_term_env,
            v_s);
          node4 match {
            case t_DeclPairLattice.p_table_entry(_,v_0,v_value) => {
              if (new M__basic_2[ T_IntegerLattice](t_IntegerLattice).v__op_0(eval_a1_IntegerLattice_variable_value(
                node,
                v_term_env,
                {
                  val node6 = t_DeclPairLattice.v_select(v_term_env,
                    v_s);
                  node6 match {
                    case t_DeclPairLattice.p_table_entry(_,v_0,v_value) => {
                      eval_a1_IntegerLattice_variable_value(
                        node,
                        v_term_env,
                        /* circular dependency detected for self.term_val, dumping as attribute access */ a_term_val.get(v_self)
                      )
                    }
                    case _ => {
                      eval_a1_IntegerLattice_variable_value(
                        node,
                        v_term_env,
                        /* circular dependency detected for self.term_val, dumping as attribute access */ a_term_val.get(v_self)
                      )
                    }
                  }
                }

              ),
                t_IntegerLattice.v_bottom)) {
                if (eval_a2_OrLattice_variable_defined(
                  node,
                  v_term_env,
                  /* circular dependency detected for self.term_val, dumping as attribute access */ a_term_val.get(v_self),
                  {
                    val node7 = t_DeclPairLattice.v_select(v_term_env,
                      v_s);
                    node7 match {
                      case t_DeclPairLattice.p_table_entry(_,v_0,v_value) => {
                        v_value
                      }
                      case _ => {
                        v_value
                      }
                    }
                  }

                )) {
                  t_Messages.v_single(new M__basic_18[ T_String](t_String).v__op_ss("identifier ",
                    new M__basic_18[ T_String](t_String).v__op_ss(v_symbol_name(v_s),
                      " is defined but has an unknown value")))
                } else {
                  t_Messages.v_single(new M__basic_18[ T_String](t_String).v__op_ss("unknown identifier of ",
                    v_symbol_name(v_s)))
                }

              } else {
                t_Messages.v_none()
              }

            }
            case _ => {
              if (new M__basic_2[ T_IntegerLattice](t_IntegerLattice).v__op_0(eval_a1_IntegerLattice_variable_value(
                node,
                v_term_env,
                /* circular dependency detected for self.term_val, dumping as attribute access */ a_term_val.get(v_self)
              ),
                t_IntegerLattice.v_bottom)) {
                if (eval_a2_OrLattice_variable_defined(
                  node,
                  v_term_env,
                  /* circular dependency detected for self.term_val, dumping as attribute access */ a_term_val.get(v_self),
                  {
                    val node7 = t_DeclPairLattice.v_select(v_term_env,
                      v_s);
                    node7 match {
                      case t_DeclPairLattice.p_table_entry(_,v_0,v_value) => {
                        v_value
                      }
                      case _ => {
                        t_IntegerLattice.v_bottom
                      }
                    }
                  }

                )) {
                  t_Messages.v_single(new M__basic_18[ T_String](t_String).v__op_ss("identifier ",
                    new M__basic_18[ T_String](t_String).v__op_ss(v_symbol_name(v_s),
                      " is defined but has an unknown value")))
                } else {
                  t_Messages.v_single(new M__basic_18[ T_String](t_String).v__op_ss("unknown identifier of ",
                    v_symbol_name(v_s)))
                }

              } else {
                t_Messages.v_none()
              }

            }
          }
        }

      }
      case p_term_literal(v_self,v_i) => {
        t_Messages.v_none()
      }
      case _ => throw new RuntimeException("failed pattern matching: " + node)
    };
    a_term_errs.assign(node, result);
    a_term_errs.get(node);
    result
  }

  def eval_Term_term_val(node: T_Term,
                         v_term_env: T_DeclPairLattice)(implicit isInsideFixedPoint: Boolean, changed: AtomicBoolean): T_IntegerLattice = {
    if (!isInsideFixedPoint) {
      a_term_val.checkNode(node).status match {
        case Evaluation.ASSIGNED => return a_term_val.get(node)
        case _ => ()
      };
    }
    val anchor = node;
    val result = node match {
      case p_term_variable(v_self,v_s) => {
        {
          val prevIsInsideFixedPoint3 = isInsideFixedPoint;
          val prevChanged3 = changed;
          val newChanged3 = new AtomicBoolean(false);
          do {
            newChanged3.set(false);
            implicit val isInsideFixedPoint: Boolean = true;
            implicit val changed: AtomicBoolean = newChanged3;
            a_term_val.assign(node, {
              val node6 = t_DeclPairLattice.v_select(v_term_env,
                v_s);
              node6 match {
                case t_DeclPairLattice.p_table_entry(_,v_0,v_value) => {
                  eval_a1_IntegerLattice_variable_value(
                    node,
                    v_term_env,
                    /* circular dependency detected for self.term_val, dumping as attribute access */ a_term_val.get(v_self)
                  )
                }
                case _ => {
                  eval_a1_IntegerLattice_variable_value(
                    node,
                    v_term_env,
                    /* circular dependency detected for self.term_val, dumping as attribute access */ a_term_val.get(v_self)
                  )
                }
              }
            }
              , changed);
          } while (newChanged3.get && !prevIsInsideFixedPoint3)
          prevChanged3.compareAndSet(false, newChanged3.get);
          a_term_val.get(node)
        }
      }
      case p_term_literal(v_self,v_i) => {
        {
          val prevIsInsideFixedPoint3 = isInsideFixedPoint;
          val prevChanged3 = changed;
          val newChanged3 = new AtomicBoolean(false);
          do {
            newChanged3.set(false);
            implicit val isInsideFixedPoint: Boolean = true;
            implicit val changed: AtomicBoolean = newChanged3;
            a_term_val.assign(node, t_IntegerLattice.v_lift(v_i), changed);
          } while (newChanged3.get && !prevIsInsideFixedPoint3)
          prevChanged3.compareAndSet(false, newChanged3.get);
          a_term_val.get(node)
        }
      }
      case _ => throw new RuntimeException("failed pattern matching: " + node)
    };
    a_term_val.assign(node, result);
    a_term_val.get(node);
    result
  }

  def eval_Operation_op_val(node: T_Operation,
                            v_op_rval: T_IntegerLattice,
                            v_op_lval: T_IntegerLattice)(implicit isInsideFixedPoint: Boolean, changed: AtomicBoolean): T_IntegerLattice = {
    if (!isInsideFixedPoint) {
      a_op_val.checkNode(node).status match {
        case Evaluation.ASSIGNED => return a_op_val.get(node)
        case _ => ()
      };
    }
    val anchor = node;
    val result = node match {
      case p_op_add(v_self) => {
        {
          val prevIsInsideFixedPoint3 = isInsideFixedPoint;
          val prevChanged3 = changed;
          val newChanged3 = new AtomicBoolean(false);
          do {
            newChanged3.set(false);
            implicit val isInsideFixedPoint: Boolean = true;
            implicit val changed: AtomicBoolean = newChanged3;
            a_op_val.assign(node, if (v_or(new M__basic_2[ T_IntegerLattice](t_IntegerLattice).v__op_0(v_op_lval,
              t_IntegerLattice.v_bottom),
              new M__basic_2[ T_IntegerLattice](t_IntegerLattice).v__op_0(v_op_rval,
                t_IntegerLattice.v_bottom))) {
              t_IntegerLattice.v_bottom
            } else {
              t_IntegerLattice.v_applyf2(t_Integer.v_plus,
                v_op_lval,
                v_op_rval)
            }
              , changed);
          } while (newChanged3.get && !prevIsInsideFixedPoint3)
          prevChanged3.compareAndSet(false, newChanged3.get);
          a_op_val.get(node)
        }
      }
      case p_op_mul(v_self) => {
        {
          val prevIsInsideFixedPoint3 = isInsideFixedPoint;
          val prevChanged3 = changed;
          val newChanged3 = new AtomicBoolean(false);
          do {
            newChanged3.set(false);
            implicit val isInsideFixedPoint: Boolean = true;
            implicit val changed: AtomicBoolean = newChanged3;
            a_op_val.assign(node, if (v_or(new M__basic_2[ T_IntegerLattice](t_IntegerLattice).v__op_0(v_op_lval,
              t_IntegerLattice.v_bottom),
              new M__basic_2[ T_IntegerLattice](t_IntegerLattice).v__op_0(v_op_rval,
                t_IntegerLattice.v_bottom))) {
              t_IntegerLattice.v_bottom
            } else {
              t_IntegerLattice.v_applyf2(t_Integer.v_times,
                v_op_lval,
                v_op_rval)
            }
              , changed);
          } while (newChanged3.get && !prevIsInsideFixedPoint3)
          prevChanged3.compareAndSet(false, newChanged3.get);
          a_op_val.get(node)
        }
      }
      case p_op_sub(v_self) => {
        {
          val prevIsInsideFixedPoint3 = isInsideFixedPoint;
          val prevChanged3 = changed;
          val newChanged3 = new AtomicBoolean(false);
          do {
            newChanged3.set(false);
            implicit val isInsideFixedPoint: Boolean = true;
            implicit val changed: AtomicBoolean = newChanged3;
            a_op_val.assign(node, if (v_or(new M__basic_2[ T_IntegerLattice](t_IntegerLattice).v__op_0(v_op_lval,
              t_IntegerLattice.v_bottom),
              new M__basic_2[ T_IntegerLattice](t_IntegerLattice).v__op_0(v_op_rval,
                t_IntegerLattice.v_bottom))) {
              t_IntegerLattice.v_bottom
            } else {
              t_IntegerLattice.v_applyf2(t_Integer.v_minus,
                v_op_lval,
                v_op_rval)
            }
              , changed);
          } while (newChanged3.get && !prevIsInsideFixedPoint3)
          prevChanged3.compareAndSet(false, newChanged3.get);
          a_op_val.get(node)
        }
      }
      case p_op_div(v_self) => {
        {
          val prevIsInsideFixedPoint3 = isInsideFixedPoint;
          val prevChanged3 = changed;
          val newChanged3 = new AtomicBoolean(false);
          do {
            newChanged3.set(false);
            implicit val isInsideFixedPoint: Boolean = true;
            implicit val changed: AtomicBoolean = newChanged3;
            a_op_val.assign(node, if (v_or(new M__basic_2[ T_IntegerLattice](t_IntegerLattice).v__op_0(v_op_lval,
              t_IntegerLattice.v_bottom),
              new M__basic_2[ T_IntegerLattice](t_IntegerLattice).v__op_0(v_op_rval,
                t_IntegerLattice.v_bottom))) {
              t_IntegerLattice.v_bottom
            } else {
              t_IntegerLattice.v_applyf2(t_Integer.v_divide,
                v_op_lval,
                v_op_rval)
            }
              , changed);
          } while (newChanged3.get && !prevIsInsideFixedPoint3)
          prevChanged3.compareAndSet(false, newChanged3.get);
          a_op_val.get(node)
        }
      }
      case _ => throw new RuntimeException("failed pattern matching: " + node)
    };
    a_op_val.assign(node, result);
    a_op_val.get(node);
    result
  }

  def eval_Program_program_errs(node: T_Program)(implicit isInsideFixedPoint: Boolean, changed: AtomicBoolean): T_Messages = {
    if (!isInsideFixedPoint) {
      a_program_errs.checkNode(node).status match {
        case Evaluation.ASSIGNED => return a_program_errs.get(node)
        case _ => ()
      };
    }
    val anchor = node;
    val result = node match {
      case p_program(v_self,v_ds) => {
        eval_Declarations_decls_errs(
          v_ds,
          t_DeclPairLattice.v_bottom,
          eval_Declarations_decls_defs(
            v_ds,
            t_DeclPairLattice.v_bottom
          )
        )
      }
      case _ => throw new RuntimeException("failed pattern matching: " + node)
    };
    a_program_errs.assign(node, result);
    a_program_errs.get(node);
    result
  }

  def eval_a1_IntegerLattice_variable_value(node: T_Term,
                                            v_self_term_env: T_DeclPairLattice,
                                            v_self_term_val: T_IntegerLattice)(implicit isInsideFixedPoint: Boolean, changed: AtomicBoolean): T_IntegerLattice = {
    if (!isInsideFixedPoint) {
      a1_variable_value.checkNode(node).status match {
        case Evaluation.ASSIGNED => return a1_variable_value.get(node)
        case _ => ()
      };
    }
    val anchor = node;
    val result = node match {
      case p_term_variable(v_self,v_s) => {
        {
          val prevIsInsideFixedPoint7 = isInsideFixedPoint;
          val prevChanged7 = changed;
          val newChanged7 = new AtomicBoolean(false);
          do {
            newChanged7.set(false);
            implicit val isInsideFixedPoint: Boolean = true;
            implicit val changed: AtomicBoolean = newChanged7;
            a1_variable_value.assign(node, {
              val node7 = t_DeclPairLattice.v_select(v_self_term_env,
                v_s);
              node7 match {
                case t_DeclPairLattice.p_table_entry(_,v_0,v_value) => {
                  v_value
                }
                case _ => {
                  t_IntegerLattice.v_bottom
                }
              }
            }
              , changed);
          } while (newChanged7.get && !prevIsInsideFixedPoint7)
          prevChanged7.compareAndSet(false, newChanged7.get);
          a1_variable_value.get(node)
        }
      }
      case _ => throw new RuntimeException("failed pattern matching: " + node)
    };
    a1_variable_value.assign(node, result);
    a1_variable_value.get(node);
    result
  }

  def eval_a2_OrLattice_variable_defined(node: T_Term,
                                         v_self_term_env: T_DeclPairLattice,
                                         v_self_term_val: T_IntegerLattice,
                                         v_variable_value: T_IntegerLattice)(implicit isInsideFixedPoint: Boolean, changed: AtomicBoolean): T_OrLattice = {
    if (!isInsideFixedPoint) {
      a2_variable_defined.checkNode(node).status match {
        case Evaluation.ASSIGNED => return a2_variable_defined.get(node)
        case _ => ()
      };
    }
    val anchor = node;
    val result = node match {
      case p_term_variable(v_self,v_s) => {
        {
          val prevIsInsideFixedPoint8 = isInsideFixedPoint;
          val prevChanged8 = changed;
          val newChanged8 = new AtomicBoolean(false);
          do {
            newChanged8.set(false);
            implicit val isInsideFixedPoint: Boolean = true;
            implicit val changed: AtomicBoolean = newChanged8;
            a2_variable_defined.assign(node, {
              val node8 = t_DeclPairLattice.v_select(v_self_term_env,
                v_s);
              node8 match {
                case t_DeclPairLattice.p_table_entry(_,v_0,v_value) => {
                  v_true
                }
                case _ => {
                  v_false
                }
              }
            }
              , changed);
          } while (newChanged8.get && !prevIsInsideFixedPoint8)
          prevChanged8.compareAndSet(false, newChanged8.get);
          a2_variable_defined.get(node)
        }
      }
      case _ => throw new RuntimeException("failed pattern matching: " + node)
    };
    a2_variable_defined.assign(node, result);
    a2_variable_defined.get(node);
    result
  }

  override def finish() : Unit = {
    implicit val isInsideFixedPoint: Boolean = false;
    implicit val changed: AtomicBoolean = new AtomicBoolean(false);
    for (root <- t_Program.nodes) {
      eval_Program_program_errs(root);
    }
    super.finish();
  };
}

