// Generated by aps2scala version 0.3.6
import basic_implicit._;
object farrow_ubd_dynamic_implicit {
  val farrow_ubd_loaded = true;
  import symbol_implicit._;
  import table_implicit._;
  import flat_implicit._;
  import farrow_ubd_tree_implicit._;
  type T_FARROW_UBD[T_T] = T_T;
}
import farrow_ubd_dynamic_implicit._;

import symbol_implicit._;
import table_implicit._;
import flat_implicit._;
import farrow_ubd_tree_implicit._;
trait C_FARROW_UBD_DYNAMIC[T_Result, T_T] extends C_TYPE[T_Result]
  with C_FARROW_UBD_TREE[T_Result] {
  type T_IntegerLattice;
  val t_IntegerLattice : C_TYPE[T_IntegerLattice]
    with C_FLAT_LATTICE[T_IntegerLattice,T_Integer];
  type T_DeclPairLattice;
  val t_DeclPairLattice : C_TYPE[T_DeclPairLattice]
    with C_TABLE_LATTICE[T_DeclPairLattice,T_Symbol,T_IntegerLattice];
  type T_Messages;
  val t_Messages : C_TYPE[T_Messages]
    with C_SET[T_Messages,T_String];
  val v_decl_name : (T_Declaration) => T_Symbol;
  val v_decl_pair : (T_Declaration) => T_DeclPairLattice;
  val v_decl_env : (T_Declaration) => T_DeclPairLattice;
  val v_decl_errs : (T_Declaration) => T_Messages;
  val v_decls_defs : (T_Declarations) => T_DeclPairLattice;
  val v_decls_env : (T_Declarations) => T_DeclPairLattice;
  val v_decls_errs : (T_Declarations) => T_Messages;
  val v_expr_val : (T_Expression) => T_IntegerLattice;
  val v_expr_env : (T_Expression) => T_DeclPairLattice;
  val v_expr_errs : (T_Expression) => T_Messages;
  val v_term_val : (T_Term) => T_IntegerLattice;
  val v_term_env : (T_Term) => T_DeclPairLattice;
  val v_term_errs : (T_Term) => T_Messages;
  val v_op_val : (T_Operation) => T_IntegerLattice;
  val v_op_lval : (T_Operation) => T_IntegerLattice;
  val v_op_rval : (T_Operation) => T_IntegerLattice;
  val v_program_errs : (T_Program) => T_Messages;
}

class M_FARROW_UBD_DYNAMIC[T_T](name : String,val t_T : C_TYPE[T_T]
  with C_FARROW_UBD_TREE[T_T])
  extends Module(name)
    with C_FARROW_UBD_DYNAMIC[T_T,T_T]
{
  type T_Result = T_T;
  val v_equal = t_T.v_equal;
  val v_string = t_T.v_string;
  val v_assert = t_T.v_assert;
  val v_node_equivalent = t_T.v_node_equivalent;
  type T_Declaration = t_T.T_Declaration;
  val t_Declaration = t_T.t_Declaration;
  type T_Declarations = t_T.T_Declarations;
  val t_Declarations = t_T.t_Declarations;
  type T_Expression = t_T.T_Expression;
  val t_Expression = t_T.t_Expression;
  type T_Term = t_T.T_Term;
  val t_Term = t_T.t_Term;
  type T_Operation = t_T.T_Operation;
  val t_Operation = t_T.t_Operation;
  type T_Program = t_T.T_Program;
  val t_Program = t_T.t_Program;
  val p_scope = t_T.p_scope;
  val v_scope = t_T.v_scope;
  val p_decl_assign = t_T.p_decl_assign;
  val v_decl_assign = t_T.v_decl_assign;
  val p_decls_empty = t_T.p_decls_empty;
  val v_decls_empty = t_T.v_decls_empty;
  val p_decls_append = t_T.p_decls_append;
  val v_decls_append = t_T.v_decls_append;
  val p_decls_append_scope = t_T.p_decls_append_scope;
  val v_decls_append_scope = t_T.v_decls_append_scope;
  val p_expr_term = t_T.p_expr_term;
  val v_expr_term = t_T.v_expr_term;
  val p_op_add = t_T.p_op_add;
  val v_op_add = t_T.v_op_add;
  val p_op_mul = t_T.p_op_mul;
  val v_op_mul = t_T.v_op_mul;
  val p_op_sub = t_T.p_op_sub;
  val v_op_sub = t_T.v_op_sub;
  val p_op_div = t_T.p_op_div;
  val v_op_div = t_T.v_op_div;
  val p_expr_apply = t_T.p_expr_apply;
  val v_expr_apply = t_T.v_expr_apply;
  val p_term_variable = t_T.p_term_variable;
  val v_term_variable = t_T.v_term_variable;
  val p_term_literal = t_T.p_term_literal;
  val v_term_literal = t_T.v_term_literal;
  val p_program = t_T.p_program;
  val v_program = t_T.v_program;

  val t_Result : this.type = this;
  val t_IntegerLattice = new M_FLAT_LATTICE[T_Integer](
    "IntegerLattice",
    t_Integer
  )

  type T_IntegerLattice = /*TI*/T_FLAT_LATTICE[T_Integer];
  val t_DeclPairLattice = new M_TABLE_LATTICE[T_Symbol,T_IntegerLattice](
    "DeclPairLattice",
    t_Symbol,
    t_IntegerLattice
  )

  type T_DeclPairLattice = /*TI*/T_TABLE_LATTICE[T_Symbol,T_IntegerLattice];
  val t_Messages = new M_SET[T_String](
    "Messages",
    t_String
  )

  type T_Messages = /*TI*/T_SET[T_String];
  private class E_decl_name(anchor : T_Declaration) extends Evaluation[T_Declaration,T_Symbol](anchor,anchor.toString()+"."+"decl_name") {
    override def compute : ValueType = c_decl_name(anchor);
  }
  private object a_decl_name extends Attribute[T_Declaration,T_Symbol](t_Declaration,t_Symbol,"decl_name") {
    override def createEvaluation(anchor : T_Declaration) : Evaluation[T_Declaration,T_Symbol] = new E_decl_name(anchor);
  }
  val v_decl_name : T_Declaration => T_Symbol = a_decl_name.get _;

  private class E_decl_pair(anchor : T_Declaration) extends Evaluation[T_Declaration,T_DeclPairLattice](anchor,anchor.toString()+"."+"decl_pair") with CircularEvaluation[T_Declaration,T_DeclPairLattice] with CollectionEvaluation[T_Declaration,T_DeclPairLattice] {
    override def initial : T_DeclPairLattice = t_DeclPairLattice.v_initial;
    override def combine(v1 : T_DeclPairLattice, v2 : T_DeclPairLattice) = t_DeclPairLattice.v_combine(v1,v2);
    def lattice : C_LATTICE[T_DeclPairLattice] = t_DeclPairLattice;

    override def compute : ValueType = c_decl_pair(anchor);
  }
  private object a_decl_pair extends Attribute[T_Declaration,T_DeclPairLattice](t_Declaration,t_DeclPairLattice,"decl_pair") {
    override def createEvaluation(anchor : T_Declaration) : Evaluation[T_Declaration,T_DeclPairLattice] = new E_decl_pair(anchor);
  }
  val v_decl_pair : T_Declaration => T_DeclPairLattice = a_decl_pair.get _;

  private class E_decl_env(anchor : T_Declaration) extends Evaluation[T_Declaration,T_DeclPairLattice](anchor,anchor.toString()+"."+"decl_env") with CircularEvaluation[T_Declaration,T_DeclPairLattice] with CollectionEvaluation[T_Declaration,T_DeclPairLattice] {
    override def initial : T_DeclPairLattice = t_DeclPairLattice.v_initial;
    override def combine(v1 : T_DeclPairLattice, v2 : T_DeclPairLattice) = t_DeclPairLattice.v_combine(v1,v2);
    def lattice : C_LATTICE[T_DeclPairLattice] = t_DeclPairLattice;

    override def compute : ValueType = c_decl_env(anchor);
  }
  private object a_decl_env extends Attribute[T_Declaration,T_DeclPairLattice](t_Declaration,t_DeclPairLattice,"decl_env") {
    override def createEvaluation(anchor : T_Declaration) : Evaluation[T_Declaration,T_DeclPairLattice] = new E_decl_env(anchor);
  }
  val v_decl_env : T_Declaration => T_DeclPairLattice = a_decl_env.get _;

  private class E_decl_errs(anchor : T_Declaration) extends Evaluation[T_Declaration,T_Messages](anchor,anchor.toString()+"."+"decl_errs") {
    override def compute : ValueType = c_decl_errs(anchor);
  }
  private object a_decl_errs extends Attribute[T_Declaration,T_Messages](t_Declaration,t_Messages,"decl_errs") {
    override def createEvaluation(anchor : T_Declaration) : Evaluation[T_Declaration,T_Messages] = new E_decl_errs(anchor);
  }
  val v_decl_errs : T_Declaration => T_Messages = a_decl_errs.get _;

  private class E_decls_defs(anchor : T_Declarations) extends Evaluation[T_Declarations,T_DeclPairLattice](anchor,anchor.toString()+"."+"decls_defs") with CircularEvaluation[T_Declarations,T_DeclPairLattice] with CollectionEvaluation[T_Declarations,T_DeclPairLattice] {
    override def initial : T_DeclPairLattice = t_DeclPairLattice.v_initial;
    override def combine(v1 : T_DeclPairLattice, v2 : T_DeclPairLattice) = t_DeclPairLattice.v_combine(v1,v2);
    def lattice : C_LATTICE[T_DeclPairLattice] = t_DeclPairLattice;

    override def compute : ValueType = c_decls_defs(anchor);
  }
  private object a_decls_defs extends Attribute[T_Declarations,T_DeclPairLattice](t_Declarations,t_DeclPairLattice,"decls_defs") {
    override def createEvaluation(anchor : T_Declarations) : Evaluation[T_Declarations,T_DeclPairLattice] = new E_decls_defs(anchor);
  }
  val v_decls_defs : T_Declarations => T_DeclPairLattice = a_decls_defs.get _;

  private class E_decls_env(anchor : T_Declarations) extends Evaluation[T_Declarations,T_DeclPairLattice](anchor,anchor.toString()+"."+"decls_env") with CircularEvaluation[T_Declarations,T_DeclPairLattice] with CollectionEvaluation[T_Declarations,T_DeclPairLattice] {
    override def initial : T_DeclPairLattice = t_DeclPairLattice.v_initial;
    override def combine(v1 : T_DeclPairLattice, v2 : T_DeclPairLattice) = t_DeclPairLattice.v_combine(v1,v2);
    def lattice : C_LATTICE[T_DeclPairLattice] = t_DeclPairLattice;

    override def compute : ValueType = c_decls_env(anchor);
  }
  private object a_decls_env extends Attribute[T_Declarations,T_DeclPairLattice](t_Declarations,t_DeclPairLattice,"decls_env") {
    override def createEvaluation(anchor : T_Declarations) : Evaluation[T_Declarations,T_DeclPairLattice] = new E_decls_env(anchor);
  }
  val v_decls_env : T_Declarations => T_DeclPairLattice = a_decls_env.get _;

  private class E_decls_errs(anchor : T_Declarations) extends Evaluation[T_Declarations,T_Messages](anchor,anchor.toString()+"."+"decls_errs") {
    override def compute : ValueType = c_decls_errs(anchor);
  }
  private object a_decls_errs extends Attribute[T_Declarations,T_Messages](t_Declarations,t_Messages,"decls_errs") {
    override def createEvaluation(anchor : T_Declarations) : Evaluation[T_Declarations,T_Messages] = new E_decls_errs(anchor);
  }
  val v_decls_errs : T_Declarations => T_Messages = a_decls_errs.get _;

  private class E_expr_val(anchor : T_Expression) extends Evaluation[T_Expression,T_IntegerLattice](anchor,anchor.toString()+"."+"expr_val") with CircularEvaluation[T_Expression,T_IntegerLattice] {
    def lattice : C_LATTICE[T_IntegerLattice] = t_IntegerLattice;

    override def compute : ValueType = c_expr_val(anchor);
  }
  private object a_expr_val extends Attribute[T_Expression,T_IntegerLattice](t_Expression,t_IntegerLattice,"expr_val") {
    override def createEvaluation(anchor : T_Expression) : Evaluation[T_Expression,T_IntegerLattice] = new E_expr_val(anchor);
  }
  val v_expr_val : T_Expression => T_IntegerLattice = a_expr_val.get _;

  private class E_expr_env(anchor : T_Expression) extends Evaluation[T_Expression,T_DeclPairLattice](anchor,anchor.toString()+"."+"expr_env") with CircularEvaluation[T_Expression,T_DeclPairLattice] with CollectionEvaluation[T_Expression,T_DeclPairLattice] {
    override def initial : T_DeclPairLattice = t_DeclPairLattice.v_initial;
    override def combine(v1 : T_DeclPairLattice, v2 : T_DeclPairLattice) = t_DeclPairLattice.v_combine(v1,v2);
    def lattice : C_LATTICE[T_DeclPairLattice] = t_DeclPairLattice;

    override def compute : ValueType = c_expr_env(anchor);
  }
  private object a_expr_env extends Attribute[T_Expression,T_DeclPairLattice](t_Expression,t_DeclPairLattice,"expr_env") {
    override def createEvaluation(anchor : T_Expression) : Evaluation[T_Expression,T_DeclPairLattice] = new E_expr_env(anchor);
  }
  val v_expr_env : T_Expression => T_DeclPairLattice = a_expr_env.get _;

  private class E_expr_errs(anchor : T_Expression) extends Evaluation[T_Expression,T_Messages](anchor,anchor.toString()+"."+"expr_errs") {
    override def compute : ValueType = c_expr_errs(anchor);
  }
  private object a_expr_errs extends Attribute[T_Expression,T_Messages](t_Expression,t_Messages,"expr_errs") {
    override def createEvaluation(anchor : T_Expression) : Evaluation[T_Expression,T_Messages] = new E_expr_errs(anchor);
  }
  val v_expr_errs : T_Expression => T_Messages = a_expr_errs.get _;

  private class E_term_val(anchor : T_Term) extends Evaluation[T_Term,T_IntegerLattice](anchor,anchor.toString()+"."+"term_val") with CircularEvaluation[T_Term,T_IntegerLattice] {
    def lattice : C_LATTICE[T_IntegerLattice] = t_IntegerLattice;

    override def compute : ValueType = c_term_val(anchor);
  }
  private object a_term_val extends Attribute[T_Term,T_IntegerLattice](t_Term,t_IntegerLattice,"term_val") {
    override def createEvaluation(anchor : T_Term) : Evaluation[T_Term,T_IntegerLattice] = new E_term_val(anchor);
  }
  val v_term_val : T_Term => T_IntegerLattice = a_term_val.get _;

  private class E_term_env(anchor : T_Term) extends Evaluation[T_Term,T_DeclPairLattice](anchor,anchor.toString()+"."+"term_env") with CircularEvaluation[T_Term,T_DeclPairLattice] with CollectionEvaluation[T_Term,T_DeclPairLattice] {
    override def initial : T_DeclPairLattice = t_DeclPairLattice.v_initial;
    override def combine(v1 : T_DeclPairLattice, v2 : T_DeclPairLattice) = t_DeclPairLattice.v_combine(v1,v2);
    def lattice : C_LATTICE[T_DeclPairLattice] = t_DeclPairLattice;

    override def compute : ValueType = c_term_env(anchor);
  }
  private object a_term_env extends Attribute[T_Term,T_DeclPairLattice](t_Term,t_DeclPairLattice,"term_env") {
    override def createEvaluation(anchor : T_Term) : Evaluation[T_Term,T_DeclPairLattice] = new E_term_env(anchor);
  }
  val v_term_env : T_Term => T_DeclPairLattice = a_term_env.get _;

  private class E_term_errs(anchor : T_Term) extends Evaluation[T_Term,T_Messages](anchor,anchor.toString()+"."+"term_errs") {
    override def compute : ValueType = c_term_errs(anchor);
  }
  private object a_term_errs extends Attribute[T_Term,T_Messages](t_Term,t_Messages,"term_errs") {
    override def createEvaluation(anchor : T_Term) : Evaluation[T_Term,T_Messages] = new E_term_errs(anchor);
  }
  val v_term_errs : T_Term => T_Messages = a_term_errs.get _;

  private class E_op_val(anchor : T_Operation) extends Evaluation[T_Operation,T_IntegerLattice](anchor,anchor.toString()+"."+"op_val") with CircularEvaluation[T_Operation,T_IntegerLattice] {
    def lattice : C_LATTICE[T_IntegerLattice] = t_IntegerLattice;

    override def compute : ValueType = c_op_val(anchor);
  }
  private object a_op_val extends Attribute[T_Operation,T_IntegerLattice](t_Operation,t_IntegerLattice,"op_val") {
    override def createEvaluation(anchor : T_Operation) : Evaluation[T_Operation,T_IntegerLattice] = new E_op_val(anchor);
  }
  val v_op_val : T_Operation => T_IntegerLattice = a_op_val.get _;

  private class E_op_lval(anchor : T_Operation) extends Evaluation[T_Operation,T_IntegerLattice](anchor,anchor.toString()+"."+"op_lval") with CircularEvaluation[T_Operation,T_IntegerLattice] {
    def lattice : C_LATTICE[T_IntegerLattice] = t_IntegerLattice;

    override def compute : ValueType = c_op_lval(anchor);
  }
  private object a_op_lval extends Attribute[T_Operation,T_IntegerLattice](t_Operation,t_IntegerLattice,"op_lval") {
    override def createEvaluation(anchor : T_Operation) : Evaluation[T_Operation,T_IntegerLattice] = new E_op_lval(anchor);
  }
  val v_op_lval : T_Operation => T_IntegerLattice = a_op_lval.get _;

  private class E_op_rval(anchor : T_Operation) extends Evaluation[T_Operation,T_IntegerLattice](anchor,anchor.toString()+"."+"op_rval") with CircularEvaluation[T_Operation,T_IntegerLattice] {
    def lattice : C_LATTICE[T_IntegerLattice] = t_IntegerLattice;

    override def compute : ValueType = c_op_rval(anchor);
  }
  private object a_op_rval extends Attribute[T_Operation,T_IntegerLattice](t_Operation,t_IntegerLattice,"op_rval") {
    override def createEvaluation(anchor : T_Operation) : Evaluation[T_Operation,T_IntegerLattice] = new E_op_rval(anchor);
  }
  val v_op_rval : T_Operation => T_IntegerLattice = a_op_rval.get _;

  private class E_program_errs(anchor : T_Program) extends Evaluation[T_Program,T_Messages](anchor,anchor.toString()+"."+"program_errs") {
    override def compute : ValueType = c_program_errs(anchor);
  }
  private object a_program_errs extends Attribute[T_Program,T_Messages](t_Program,t_Messages,"program_errs") {
    override def createEvaluation(anchor : T_Program) : Evaluation[T_Program,T_Messages] = new E_program_errs(anchor);
  }
  val v_program_errs : T_Program => T_Messages = a_program_errs.get _;

  private class E1_variable_value(anchor : t_Result.T_Term) extends Evaluation[t_Result.T_Term,T_IntegerLattice](anchor,anchor.toString()+"."+"variable_value") with CircularEvaluation[t_Result.T_Term,T_IntegerLattice] {
    def lattice : C_LATTICE[T_IntegerLattice] = t_IntegerLattice;

    override def compute : ValueType = c1_variable_value(anchor);
  }
  private object a1_variable_value extends Attribute[t_Result.T_Term,T_IntegerLattice](t_Result.t_Term,t_IntegerLattice,"variable_value") {
    override def createEvaluation(anchor : t_Result.T_Term) : Evaluation[t_Result.T_Term,T_IntegerLattice] = new E1_variable_value(anchor);
  }
  private class E2_variable_defined(anchor : t_Result.T_Term) extends Evaluation[t_Result.T_Term,T_OrLattice](anchor,anchor.toString()+"."+"variable_defined") with CircularEvaluation[t_Result.T_Term,T_OrLattice] {
    def lattice : C_LATTICE[T_OrLattice] = t_OrLattice;

    override def compute : ValueType = c2_variable_defined(anchor);
  }
  private object a2_variable_defined extends Attribute[t_Result.T_Term,T_OrLattice](t_Result.t_Term,t_OrLattice,"variable_defined") {
    override def createEvaluation(anchor : t_Result.T_Term) : Evaluation[t_Result.T_Term,T_OrLattice] = new E2_variable_defined(anchor);
  }
  def c1_variable_value(anchor : Any) : T_IntegerLattice = {
    anchor match {
      case p_term_variable(v_self,v_s) => {
        t_DeclPairLattice.v_select(v_term_env(v_self),
          v_s) match {
          case t_DeclPairLattice.p_table_entry(_,v_0,v_value) => {
            return v_value;
          }
          case _ => {}
        }
        return t_IntegerLattice.v_bottom;
      }
    }
  }
  def c2_variable_defined(anchor : Any) : T_OrLattice = {
    anchor match {
      case p_term_variable(v_self,v_s) => {
        t_DeclPairLattice.v_select(v_term_env(v_self),
          v_s) match {
          case t_DeclPairLattice.p_table_entry(_,v_0,v_value) => {
            return v_true;
          }
          case _ => {}
        }
        return v_false;
      }
    }
  }
  def c_decl_name(anode : T_Declaration) : T_Symbol = {
    val anchor = anode;
    anchor match {
      case p_decl_assign(v_self,v_s,v_e) => {
        if (anode eq v_self) return v_s;
      }
      case _ => {}
    }
    throw Evaluation.UndefinedAttributeException(anode.toString()+".decl_name");
  }
  def c_decl_pair(anode : T_Declaration) : T_DeclPairLattice = {
    var collection : T_DeclPairLattice = t_DeclPairLattice.v_initial;
    for (anchor <- t_Result.t_Declaration.nodes) anchor match {
      case p_decl_assign(v_self,v_s,v_e) => {
        if (anode eq v_self) collection = t_DeclPairLattice.v_combine(collection,t_DeclPairLattice.v_table_entry(v_s,
          v_expr_val(v_e)));
      }
      case _ => {}
    }
    return collection;
  }
  def c_decl_env(anode : T_Declaration) : T_DeclPairLattice = {
    var collection : T_DeclPairLattice = t_DeclPairLattice.v_initial;
    for (anchor <- t_Result.t_Declarations.nodes) anchor match {
      case p_decls_append(v_self,v_ds,v_d) => {
        if (anode eq v_d) collection = t_DeclPairLattice.v_combine(collection,v_decls_env(v_self));
      }
      case _ => {}
    }
    return collection;
  }
  def c_decl_errs(anode : T_Declaration) : T_Messages = {
    val anchor = anode;
    anchor match {
      case p_decl_assign(v_self,v_s,v_e) => {
        if (anode eq v_self) return v_expr_errs(v_e);
      }
      case _ => {}
    }
    throw Evaluation.UndefinedAttributeException(anode.toString()+".decl_errs");
  }
  def c_decls_defs(anode : T_Declarations) : T_DeclPairLattice = {
    var collection : T_DeclPairLattice = t_DeclPairLattice.v_initial;
    for (anchor <- t_Result.t_Declarations.nodes) anchor match {
      case p_scope(v_self,v_ds) => {
        if (anode eq v_self) collection = t_DeclPairLattice.v_combine(collection,v_decls_defs(v_ds));
      }
      case _ => {}
    }
    for (anchor <- t_Result.t_Declarations.nodes) anchor match {
      case p_decls_empty(v_self) => {
        if (anode eq v_self) collection = t_DeclPairLattice.v_combine(collection,t_DeclPairLattice.v_bottom);
      }
      case _ => {}
    }
    for (anchor <- t_Result.t_Declarations.nodes) anchor match {
      case p_decls_append(v_self,v_ds,v_d) => {
        t_DeclPairLattice.v_select(v_decls_defs(v_ds),
          v_decl_name(v_d)) match {
          case t_DeclPairLattice.p_table_entry(_,v_0,v_value) => {
            if (anode eq v_self) collection = t_DeclPairLattice.v_combine(collection,v_decls_defs(v_ds));
          }
          case _ => {
            if (anode eq v_self) collection = t_DeclPairLattice.v_combine(collection,t_DeclPairLattice.v_join(v_decls_defs(v_ds),
              v_decl_pair(v_d)));
          }
        }
      }
      case _ => {}
    }
    for (anchor <- t_Result.t_Declarations.nodes) anchor match {
      case p_decls_append_scope(v_self,v_ds,v_inner) => {
        if (anode eq v_self) collection = t_DeclPairLattice.v_combine(collection,t_DeclPairLattice.v_join(v_decls_defs(v_ds),
          v_decls_defs(v_inner)));
      }
      case _ => {}
    }
    return collection;
  }
  def c_decls_env(anode : T_Declarations) : T_DeclPairLattice = {
    var collection : T_DeclPairLattice = t_DeclPairLattice.v_initial;
    for (anchor <- t_Result.t_Declarations.nodes) anchor match {
      case p_scope(v_self,v_ds) => {
        if (anode eq v_ds) collection = t_DeclPairLattice.v_combine(collection,v_decls_defs(v_ds));
      }
      case _ => {}
    }
    for (anchor <- t_Result.t_Declarations.nodes) anchor match {
      case p_decls_append(v_self,v_ds,v_d) => {
        if (anode eq v_ds) collection = t_DeclPairLattice.v_combine(collection,v_decls_env(v_self));
      }
      case _ => {}
    }
    for (anchor <- t_Result.t_Declarations.nodes) anchor match {
      case p_decls_append_scope(v_self,v_ds,v_inner) => {
        if (anode eq v_ds) collection = t_DeclPairLattice.v_combine(collection,v_decls_env(v_self));
        if (anode eq v_inner) collection = t_DeclPairLattice.v_combine(collection,v_decls_defs(v_inner));
      }
      case _ => {}
    }
    for (anchor <- t_Result.t_Program.nodes) anchor match {
      case p_program(v_self,v_ds) => {
        if (anode eq v_ds) collection = t_DeclPairLattice.v_combine(collection,t_DeclPairLattice.v_bottom);
      }
      case _ => {}
    }
    return collection;
  }
  def c_decls_errs(anode : T_Declarations) : T_Messages = {
    val anchor = anode;
    anchor match {
      case p_scope(v_self,v_ds) => {
        if (anode eq v_self) return v_decls_errs(v_ds);
      }
      case _ => {}
    }
    anchor match {
      case p_decls_empty(v_self) => {
        if (anode eq v_self) return t_Messages.v_none();
      }
      case _ => {}
    }
    anchor match {
      case p_decls_append(v_self,v_ds,v_d) => {
        t_DeclPairLattice.v_select(v_decls_defs(v_ds),
          v_decl_name(v_d)) match {
          case t_DeclPairLattice.p_table_entry(_,v_0,v_value) => {
            if (anode eq v_self) return new M__basic_19[ T_String,T_Messages](t_String,t_Messages).v__op_5w(new M__basic_19[ T_String,T_Messages](t_String,t_Messages).v__op_5w(t_Messages.v_single(new M__basic_18[ T_String](t_String).v__op_ss("identifier ",
              new M__basic_18[ T_String](t_String).v__op_ss(v_symbol_name(v_decl_name(v_d)),
                " is multiply defined"))),
              v_decls_errs(v_ds)),
              v_decl_errs(v_d));
          }
          case _ => {
            if (anode eq v_self) return new M__basic_19[ T_String,T_Messages](t_String,t_Messages).v__op_5w(v_decls_errs(v_ds),
              v_decl_errs(v_d));
          }
        }
      }
      case _ => {}
    }
    anchor match {
      case p_decls_append_scope(v_self,v_ds,v_inner) => {
        if (anode eq v_self) return new M__basic_19[ T_String,T_Messages](t_String,t_Messages).v__op_5w(v_decls_errs(v_ds),
          v_decls_errs(v_inner));
      }
      case _ => {}
    }
    throw Evaluation.UndefinedAttributeException(anode.toString()+".decls_errs");
  }
  def c_expr_val(anode : T_Expression) : T_IntegerLattice = {
    val anchor = anode;
    anchor match {
      case p_expr_term(v_self,v_t) => {
        if (anode eq v_self) return v_term_val(v_t);
      }
      case _ => {}
    }
    anchor match {
      case p_expr_apply(v_self,v_e,v_op,v_t) => {
        if (anode eq v_self) return v_op_val(v_op);
      }
      case _ => {}
    }
    throw Evaluation.UndefinedAttributeException(anode.toString()+".expr_val");
  }
  def c_expr_env(anode : T_Expression) : T_DeclPairLattice = {
    var collection : T_DeclPairLattice = t_DeclPairLattice.v_initial;
    for (anchor <- t_Result.t_Declaration.nodes) anchor match {
      case p_decl_assign(v_self,v_s,v_e) => {
        if (anode eq v_e) collection = t_DeclPairLattice.v_combine(collection,v_decl_env(v_self));
      }
      case _ => {}
    }
    for (anchor <- t_Result.t_Expression.nodes) anchor match {
      case p_expr_apply(v_self,v_e,v_op,v_t) => {
        if (anode eq v_e) collection = t_DeclPairLattice.v_combine(collection,v_expr_env(v_self));
      }
      case _ => {}
    }
    return collection;
  }
  def c_expr_errs(anode : T_Expression) : T_Messages = {
    val anchor = anode;
    anchor match {
      case p_expr_term(v_self,v_t) => {
        if (anode eq v_self) return v_term_errs(v_t);
      }
      case _ => {}
    }
    anchor match {
      case p_expr_apply(v_self,v_e,v_op,v_t) => {
        if (anode eq v_self) return new M__basic_19[ T_String,T_Messages](t_String,t_Messages).v__op_5w(v_expr_errs(v_e),
          v_term_errs(v_t));
      }
      case _ => {}
    }
    throw Evaluation.UndefinedAttributeException(anode.toString()+".expr_errs");
  }
  def c_term_val(anode : T_Term) : T_IntegerLattice = {
    val anchor = anode;
    anchor match {
      case p_term_variable(v_self,v_s) => {
        if (anode eq v_self) return a1_variable_value.get(anchor);
      }
      case _ => {}
    }
    anchor match {
      case p_term_literal(v_self,v_i) => {
        if (anode eq v_self) return t_IntegerLattice.v_lift(v_i);
      }
      case _ => {}
    }
    throw Evaluation.UndefinedAttributeException(anode.toString()+".term_val");
  }
  def c_term_env(anode : T_Term) : T_DeclPairLattice = {
    var collection : T_DeclPairLattice = t_DeclPairLattice.v_initial;
    for (anchor <- t_Result.t_Expression.nodes) anchor match {
      case p_expr_term(v_self,v_t) => {
        if (anode eq v_t) collection = t_DeclPairLattice.v_combine(collection,v_expr_env(v_self));
      }
      case _ => {}
    }
    for (anchor <- t_Result.t_Expression.nodes) anchor match {
      case p_expr_apply(v_self,v_e,v_op,v_t) => {
        if (anode eq v_t) collection = t_DeclPairLattice.v_combine(collection,v_expr_env(v_self));
      }
      case _ => {}
    }
    return collection;
  }
  def c_term_errs(anode : T_Term) : T_Messages = {
    val anchor = anode;
    anchor match {
      case p_term_variable(v_self,v_s) => {
        { val cond = new M__basic_2[ T_IntegerLattice](t_IntegerLattice).v__op_0(a1_variable_value.get(anchor),
          t_IntegerLattice.v_bottom);
          if (cond) {
            { val cond = a2_variable_defined.get(anchor);
              if (cond) {
                if (anode eq v_self) return t_Messages.v_single(new M__basic_18[ T_String](t_String).v__op_ss("identifier ",
                  new M__basic_18[ T_String](t_String).v__op_ss(v_symbol_name(v_s),
                    " is defined but has an unknown value")));
              }
              if (!cond) {
                if (anode eq v_self) return t_Messages.v_single(new M__basic_18[ T_String](t_String).v__op_ss("unknown identifier of ",
                  v_symbol_name(v_s)));
              }
            }
          }
          if (!cond) {
            if (anode eq v_self) return t_Messages.v_none();
          }
        }
      }
      case _ => {}
    }
    anchor match {
      case p_term_literal(v_self,v_i) => {
        if (anode eq v_self) return t_Messages.v_none();
      }
      case _ => {}
    }
    throw Evaluation.UndefinedAttributeException(anode.toString()+".term_errs");
  }
  def c_op_val(anode : T_Operation) : T_IntegerLattice = {
    val anchor = anode;
    anchor match {
      case p_op_add(v_self) => {
        { val cond = v_or(new M__basic_2[ T_IntegerLattice](t_IntegerLattice).v__op_0(v_op_lval(v_self),
          t_IntegerLattice.v_bottom),
          new M__basic_2[ T_IntegerLattice](t_IntegerLattice).v__op_0(v_op_rval(v_self),
            t_IntegerLattice.v_bottom));
          if (cond) {
            if (anode eq v_self) return t_IntegerLattice.v_bottom;
          }
          if (!cond) {
            if (anode eq v_self) return t_IntegerLattice.v_applyf2(t_Integer.v_plus,
              v_op_lval(v_self),
              v_op_rval(v_self));
          }
        }
      }
      case _ => {}
    }
    anchor match {
      case p_op_mul(v_self) => {
        { val cond = v_or(new M__basic_2[ T_IntegerLattice](t_IntegerLattice).v__op_0(v_op_lval(v_self),
          t_IntegerLattice.v_bottom),
          new M__basic_2[ T_IntegerLattice](t_IntegerLattice).v__op_0(v_op_rval(v_self),
            t_IntegerLattice.v_bottom));
          if (cond) {
            if (anode eq v_self) return t_IntegerLattice.v_bottom;
          }
          if (!cond) {
            if (anode eq v_self) return t_IntegerLattice.v_applyf2(t_Integer.v_times,
              v_op_lval(v_self),
              v_op_rval(v_self));
          }
        }
      }
      case _ => {}
    }
    anchor match {
      case p_op_sub(v_self) => {
        { val cond = v_or(new M__basic_2[ T_IntegerLattice](t_IntegerLattice).v__op_0(v_op_lval(v_self),
          t_IntegerLattice.v_bottom),
          new M__basic_2[ T_IntegerLattice](t_IntegerLattice).v__op_0(v_op_rval(v_self),
            t_IntegerLattice.v_bottom));
          if (cond) {
            if (anode eq v_self) return t_IntegerLattice.v_bottom;
          }
          if (!cond) {
            if (anode eq v_self) return t_IntegerLattice.v_applyf2(t_Integer.v_minus,
              v_op_lval(v_self),
              v_op_rval(v_self));
          }
        }
      }
      case _ => {}
    }
    anchor match {
      case p_op_div(v_self) => {
        { val cond = v_or(new M__basic_2[ T_IntegerLattice](t_IntegerLattice).v__op_0(v_op_lval(v_self),
          t_IntegerLattice.v_bottom),
          new M__basic_2[ T_IntegerLattice](t_IntegerLattice).v__op_0(v_op_rval(v_self),
            t_IntegerLattice.v_bottom));
          if (cond) {
            if (anode eq v_self) return t_IntegerLattice.v_bottom;
          }
          if (!cond) {
            if (anode eq v_self) return t_IntegerLattice.v_applyf2(t_Integer.v_divide,
              v_op_lval(v_self),
              v_op_rval(v_self));
          }
        }
      }
      case _ => {}
    }
    throw Evaluation.UndefinedAttributeException(anode.toString()+".op_val");
  }
  def c_op_lval(anode : T_Operation) : T_IntegerLattice = {
    val anchor = anode.parent;
    if (!(anchor eq null)) {
      val anchorNodes = anchor.myType.nodes;
      if (anchorNodes == t_Result.t_Expression.nodes) anchor match {
        case p_expr_apply(v_self,v_e,v_op,v_t) => {
          if (anode eq v_op) return v_expr_val(v_e);
        }
        case _ => {}
      }
    }
    throw Evaluation.UndefinedAttributeException(anode.toString()+".op_lval");
  }
  def c_op_rval(anode : T_Operation) : T_IntegerLattice = {
    val anchor = anode.parent;
    if (!(anchor eq null)) {
      val anchorNodes = anchor.myType.nodes;
      if (anchorNodes == t_Result.t_Expression.nodes) anchor match {
        case p_expr_apply(v_self,v_e,v_op,v_t) => {
          if (anode eq v_op) return v_term_val(v_t);
        }
        case _ => {}
      }
    }
    throw Evaluation.UndefinedAttributeException(anode.toString()+".op_rval");
  }
  def c_program_errs(anode : T_Program) : T_Messages = {
    val anchor = anode;
    anchor match {
      case p_program(v_self,v_ds) => {
        if (anode eq v_self) return v_decls_errs(v_ds);
      }
      case _ => {}
    }
    throw Evaluation.UndefinedAttributeException(anode.toString()+".program_errs");
  }
  override def finish() : Unit = {
    a_decl_name.finish;
    a_decl_pair.finish;
    a_decl_env.finish;
    a_decl_errs.finish;
    a_decls_defs.finish;
    a_decls_env.finish;
    a_decls_errs.finish;
    a_expr_val.finish;
    a_expr_env.finish;
    a_expr_errs.finish;
    a_term_val.finish;
    a_term_env.finish;
    a_term_errs.finish;
    a_op_val.finish;
    a_op_lval.finish;
    a_op_rval.finish;
    a_program_errs.finish;
    super.finish();
  }

}

